<?php
/**
 * @var $lang_url;
 * @var $parent_keyword;
 * @var $keyword;
 */
?>
<?php if(!$isMobile){ ?>
<div class="breadcrumbs black">
    <div class="container">
        <a href="<?php echo $this->url->get($lang_url); ?>" target="_self" title="<?php echo htmlentities(defined('txt_menu_home') ? txt_menu_home : ''); ?>">
            <?php echo defined('txt_menu_home') ? txt_menu_home : '' ?>
        </a>
        <a href="<?php echo $this->url->get($lang_url.'/'.$parent_keyword.'/'.$keyword); ?>" target="_self" title="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>">
            <?php echo isset($menu_bread) ? $menu_bread : '' ?>
        </a>
    </div>
</div>
<?php } ?>
<div class="pd-style">
    <div class="container">
        <h1 class="text-center text-uppercase"><?php echo isset($menu_bread) ? $menu_bread : '' ?></h1>
        <div class="content-format">
            <?php echo isset($ar_content) ? $ar_content : '' ?>
        </div>
    </div>
</div>