<?php
/**
 * @var $lang_url ;
 * @var $parent_keyword ;
 * @var $isMobile ;
 * @var $list_articles ;
 * @var \Bincg\Models\BinArticle[] $articles
 */
?>
<?php if (!$isMobile) { ?>
    <div class="breadcrumbs">
        <div class="container">
            <a href="<?php echo $this->url->get($lang_url); ?>" target="_self"
               title="<?php echo htmlentities(defined('txt_menu_home') ? txt_menu_home : ''); ?>">
                <?php echo defined('txt_menu_home') ? txt_menu_home : '' ?>
            </a>
            <a href="<?php echo $this->url->get($lang_url . '/' . $parent_keyword); ?>" target="_self"
               title="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>">
                <?php echo isset($menu_bread) ? $menu_bread : '' ?>
            </a>
        </div>
    </div>
<?php } ?>
<?php $this->view->partial('shared/layoutbanner'); ?>

<?php echo isset($ar_content) ? $ar_content : ''; ?>

<?php if (count($list_articles) > 0) { ?>

    <div class="padding-block lazyload sustainability-summary-banner d-flex align-items-center"
         data-bgset="<?php echo $this->url->getStatic('frontend/'); ?>images/csr-sustainability/sustainability-banner-3-xs.jpg [(max-width: 991px)] |
            <?php echo $this->url->getStatic('frontend/'); ?>images/csr-sustainability/sustainability-banner-3-lg.jpg"
    >
        <div class="container">
            <div class="row">
                <?php foreach ($list_articles as $article) { ?>
                    <div class="col-lg-4 mb-20">
                        <a class="square-box-link"
                           href="<?php echo $this->url->get($lang_url . '/corporate-social-responsibility/' . $article->getArticleKeyword()); ?>"
                           title="<?php echo strip_tags($article->getArticleName()) ?>" target="_self">
                            <?php echo strip_tags($article->getArticleName()) ?>
                        </a>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>

<?php } ?>

