<?php
/**
 * @var $location_code
 * @var $lang_code
 * @var $lang_url
 * @var Bincg\Models\BinArticle $article
 */
?>
<?php
$url_site_schema = defined('URL_SITE') ? URL_SITE.'/'.$lang_url : '';
$name_site_schema = defined('txt_brand_name') ? str_replace('"',"'",txt_brand_name) : '';
$logo_site_schema = defined('schema_logo_png') ? schema_logo_png : '';
$text_schema_social = defined('txt_schema_global_social') ? txt_schema_global_social : '';
if(isset($locationByLoAndLa)) {
    if($locationByLoAndLa){
        if(strlen($locationByLoAndLa->getLocationSchemaSocial()) > 0){
            $text_schema_social = $locationByLoAndLa->getLocationSchemaSocial();
        }
    }
}
$href_article_schema = '';
$name_article = '';
if($article){
    $name_article = $this->my->replaceQuotes($article->getArticleName());
    $href_article_schema = URL_SITE.'/'.$lang_url.'/'.$parent_keyword.'/'.$article->getArticleKeyword();
    ?>
    <script type="application/ld+json">
    {
        "@context": "https://schema.org",
	    "@graph": [
	        {
                "@type": "Organization",
                "@id": "<?php echo $href_article_schema; ?>",
                "name": "<?php echo $name_site_schema; ?>",
                "url": "<?php echo $url_site_schema; ?>",
                <?php if(strlen($text_schema_social)>0){ ?>
                    "sameAs": [
                        <?php echo $text_schema_social; ?>
                    ],
                <?php } ?>
                "logo": {
                    "@type": "ImageObject",
                    "@id": "<?php echo $url_site_schema; ?>/#logo",
                    "inLanguage": "<?php echo $lang_code; ?>",
                    "url": "<?php echo defined('schema_logo_png') ? schema_logo_png : '' ?>",
                    "width": 122,
                    "height": 42,
                    "caption": "<?php echo $name_site_schema; ?>"
                },
                "image": {
                    "@id": "<?php echo $url_site_schema; ?>/#logo"
                }
            }, {
                "@type": "WebSite",
                "@id": "<?php echo $url_site_schema; ?>/#website",
                "url": "<?php echo $url_site_schema; ?>/",
                "name": "<?php echo $name_site_schema; ?>",
                "inLanguage": "<?php echo $lang_code; ?>",
                "description": "<?php if(isset($meta_descript)) {echo $meta_descript;} ?>",
                "publisher": {
                    "@id": "<?php echo $url_site_schema; ?>/#organization"
                }
            }, {
                "@type": "ImageObject",
                "@id": "<?php echo $href_article_schema; ?>/#primaryimage",
                "inLanguage": "<?php echo $lang_code; ?>",
                "url": "<?php echo isset($meta_social_image) ? $meta_social_image : ''; ?>",
                "width": 1920,
                "height": 960,
                "caption": "<?php echo $name_article; ?>"
            }, {
                "@type": "WebPage",
                "@id": "<?php echo $href_article_schema; ?>/#webpage",
                "url": "<?php echo $href_article_schema; ?>",
                "name": "<?php echo $name_article; ?>",
                "isPartOf": {
                    "@id": "<?php echo $url_site_schema; ?>/#website"
                },
                "inLanguage": "<?php echo $lang_code; ?>",
                "primaryImageOfPage": {
                    "@id": "<?php echo $href_article_schema; ?>/#primaryimage"
                },
                "description": "<?php if(isset($meta_descript)) {echo $meta_descript;} ?>"
            },
            {
                "@type": "Article",
                "@id": "<?php echo $href_article_schema ?>",
                "headline": "<?php echo $this->my->replaceQuotes($name_article) ?>",
                "alternativeHeadline": "<?php echo $this->my->replaceQuotes($article->getArticleTitle()) ?>",
                "image": "<?php echo isset($meta_social_image) ? $meta_social_image : ''; ?>",
                "author": "<?php echo defined('txt_brand_name') ? $this->my->replaceQuotes(txt_brand_name) : ''; ?>",
                "award": "<?php echo defined('schema_award') ? schema_award : ''; ?>",
                "editor": "<?php echo defined('txt_brand_name') ? $this->my->replaceQuotes(txt_brand_name) : ''; ?>",
                "genre": "search engine optimization",
                "keywords": "<?php echo $this->my->replaceQuotes($article->getArticleMetaKeyword()) ?>",
                "inLanguage" : "<?php echo $lang_code ?>",
                "wordcount": "<?php echo str_word_count($ar_content); ?>",
                "publisher": {
                    "@type": "Organization",
                    "name": "<?php echo defined('txt_brand_name') ? $this->my->replaceQuotes(txt_brand_name) : ''; ?>",
                    "logo": {
                        "@type": "ImageObject",
                        "url": "<?php echo defined('schema_logo_png') ? schema_logo_png : '' ?>"
                    }
                },
                "datePublished": "<?php echo $this->my->formatDateYMD($article->getArticleInsertTime()) ?>",
                "dateCreated": "<?php echo $this->my->formatDateYMD($article->getArticleInsertTime()) ?>",
                "dateModified": "<?php echo $this->my->formatDateYMD($article->getArticleUpdateTime()) ?>",
                "description": "<?php echo $this->my->replaceQuotes($article->getArticleMetaDescription()) ?>",
                "articleBody": "<?php echo $this->my->replaceQuotes($ar_content) ?>",
                "mainEntityOfPage": {
                    "@type": "WebPage",
                    "@id": "<?php echo $href_article_schema ?>"
                }
            }
        ]
    }
</script>
<?php } ?>