<?php
/**
 * @var $lang_url;
 * @var $lang_code;
 * @var $lang_url_slashed;
 * @var $parent_keyword;
 */
?>
<?php if(!$isMobile){ ?>
<div class="breadcrumbs">
    <div class="container">
        <a href="<?php echo $this->url->get($lang_url); ?>" target="_self" title="<?php echo htmlentities(defined('txt_menu_home') ? txt_menu_home : ''); ?>">
            <?php echo defined('txt_menu_home') ? txt_menu_home : '' ?>
        </a>
        <a href="<?php echo $this->url->get($lang_url.'/'.$parent_keyword); ?>" target="_self" title="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>">
            <?php echo isset($menu_bread) ? $menu_bread : '' ?>
        </a>
    </div>
</div>
<?php } ?>
<?php if (defined('PROGRAMMABLE_SEARCH_ENGINE') && PROGRAMMABLE_SEARCH_ENGINE) { ?>
    <div id="carouselExampleControls" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <?php if(!$isMobileOnly) { ?>
                    <img class="w-100 lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $this->url->getStatic('frontend/'); ?>images/banner-search-page.jpg" alt="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>" title="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>">
                <?php }else{ ?>
                    <img class="w-100 lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $this->url->getStatic('frontend/'); ?>images/banner-search-page-xs.jpg" alt="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>" title="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>">
                <?php } ?>
                <div class="caption-banner text-center">
                    <div class="container">
                        <h1 class="caption-title mb-5"><?php echo isset($menu_bread) ? $menu_bread : '' ?></h1>
                        <div class="form-group mb-lg-0">
                            <div class="group-search-google">
                                <div class="gcse-searchbox"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="padding-block">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mx-auto">
                    <div class="gcse-searchresults" data-cr="country<?php echo strtoupper($location_code) ?>" data-enableAutoComplete="true" data-queryParameterName="q" data-autoCompleteValidLanguages="<?php echo $lang_code; ?>" data-enableHistory="true" data-autoCompleteMaxCompletions="5" data-autoCompleteMatchType='any' data-as_sitesearch="www.<?php echo $this->globalVariable->website.'/'.$location_code.'/'.$lang_code ?>"></div>
                </div>
            </div>
        </div>
    </div>
<?php } else { ?>
<div id="carouselExampleControls" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <?php if(!$isMobileOnly) { ?>
                <img class="w-100 lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $this->url->getStatic('frontend/'); ?>images/banner-search-page.jpg" alt="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>" title="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>">
            <?php }else{ ?>
                <img class="w-100 lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $this->url->getStatic('frontend/'); ?>images/banner-search-page-xs.jpg" alt="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>" title="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>">
            <?php } ?>
            <div class="caption-banner text-center">
                <div class="container">
                    <h1 class="caption-title mb-5"><?php echo isset($menu_bread) ? $menu_bread : '' ?></h1>
                    <form action="<?php echo $this->url->get($lang_url.'/search'); ?>" class="m-0 row search">
                        <div class="col-lg-4">
                            <div class="form-group mb-lg-0">
                                <select id="slType" name="slType" class="form-control">
                                    <option value="0"><?php echo defined('txt_select_category') ? txt_select_category : '' ?></option>
                                    <?php echo isset($select_type) ? $select_type : ""; ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="form-group mb-lg-0">
                                <div class="d-flex flex-mobile-wrap">
                                    <input type="search" maxlength="255" value="<?php echo $keyword; ?>" id="txtSearch" name="keyword" class="form-control searchsuggest" placeholder="<?php echo defined('txt_please_type_keyword') ? txt_please_type_keyword : '' ?>">
                                    <button type="submit" class="btn btn-main ml-lg-2 mt-3 mt-lg-0 text-nowrap btn-shadow w-mobile-100 btn-icon-search" title="<?php echo defined('btn_search') ? btn_search : '' ?>" id="btSearch" onclick="return checkform()">
                                        <img class="search-default-icon" src="<?php echo $this->url->getStatic('frontend/'); ?>images/icon-search-white.svg" alt="<?php echo htmlentities(defined('btn_search') ? btn_search : '') ?>" title="<?php echo htmlentities(defined('btn_search') ? btn_search : '') ?>">
                                        <img class="search-red-icon" src="<?php echo $this->url->getStatic('frontend/'); ?>images/icon-search-red.svg" alt="<?php echo htmlentities(defined('btn_search') ? btn_search : '') ?>" title="<?php echo htmlentities(defined('btn_search') ? btn_search : '') ?>">
                                        <?php echo defined('btn_search') ? btn_search : '' ?>
                                    </button>
                                </div>
                            </div>
                            <p class="text-danger msg-keyword"></p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="padding-block">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <h2 class="text-black mb-3">
                    <?php if(!isset($message)) {
                        if(isset($list_search) && ($totalItems > 0)){ ?>
                            <?php echo defined('txt_count_search_result') ? str_replace('|||COUNT|||',$totalItems,txt_count_search_result) : ''; ?>
                            “<span class="text-main"><?php echo $keyword ?></span>”
                        <?php } else { echo defined('txt_no_result_search') ? txt_no_result_search : ''; }
                    } ?>
                </h2>
                <?php
                if(isset($message))
                {
                    ?>
                    <div class="alert alert-danger">
                        <?php echo $message; ?>
                    </div>
                    <?php
                }
                ?>
                <?php
                foreach ($list_search as $service) {
                    ?>
                    <div class="mb-4 pb-2 border-bottom-gray">
                        <p>
                            <?php $reUrl = \Bincg\Repositories\SearchAzure::replaceUrl(isset($service['ar_url'])?$this->url->get($lang_url.$service['ar_url']):''); ?>
                            <a class="text-blue-1" href="<?php echo isset($service['ar_url'])?$this->url->get($lang_url.$service['ar_url']):''; ?>" target="_self" title="<?php echo $reUrl; ?>">
                                <?php echo $reUrl; ?>
                            </a>
                        </p>
                        <h3 class="mb-2 text-black">
                            <a href="<?php echo isset($service['ar_url'])?$this->url->get($lang_url.$service['ar_url']):''; ?>" target="_self" title="<?php echo isset($service['ar_title'])?$service['ar_title']:''; ?>">
                                <?php echo isset($service['ar_name'])?$service['ar_name']:''; ?>
                            </a>
                        </h3>
                        <p><?php echo \Bincg\Repositories\SearchAzure::_substr(isset($service['ar_content'])?$service['ar_content']:'',150); ?></p>
                    </div>
                <?php }
                ?>
                <?php if(isset($htmlPaginator) && strlen($htmlPaginator)>0){ ?>
                    <div class="padding-block">
                        <?php echo $htmlPaginator; ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<?php } ?>