<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Office Image <?php echo \Score\Repositories\Office::getNameById($formData["image_office_id"])?></h3>
    </div>
</div>
<?php if(!empty($messages['message']))
{
    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage']?>">
        <?php echo $messages['message']; ?>
    </p>
<?php }	?>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2 class="form_title"></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form name="office-image-form" id="office-image-form" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Url <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["image_url"]) ? $formData["image_url"] : "" ?>" id="txtUrl" name="txtUrl" class="form-control col-md-7 col-xs-12 <?php echo isset($messages["url"]) ? $messages["status"] : ""; ?>" type="text">
                            <span class="text-danger msg-url"><?php echo isset($messages["url"]) ? $messages["url"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Order <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["image_order"]) ? $formData["image_order"] : "" ?>" id="txtOrder" name="txtOrder" class="form-control col-md-7 col-xs-12 <?php echo isset($messages["order"]) ? $messages["status"] : ""; ?>" type="text">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Active</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($formData["image_active"]) && $formData["image_active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($formData["image_active"]) && $formData["image_active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmEmployee" id="sbmEmployee" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="<?php echo $this->url->get("/dashboard/list-office-image?office_id=".$formData["image_office_id"]); ?>">Cancel</a>
                        </div>
                    </div>
                    <script>
                        $( document ).ready(function() {
                            $('form[name=office-image-form').submit(function (event) {
                                valid = true;
                                if ($('input[name=txtUrl]').val() == '') {
                                    $('.msg-url').text('Url field is required.');
                                    $('#txtUrl').addClass("border-red");
                                    valid = false;
                                } else {
                                    $('.msg-url').text('');
                                    $('#txtUrl').removeClass("border-red");
                                }
                                if ($('input[name=txtOrder]').val() == '') {
                                    $('.msg-order').text('Order field is required.');
                                    $('#txtOrder').addClass("border-red");
                                    valid = false;
                                } else if (isNaN($('input[name=txtOrder]').val())) {
                                    $('.msg-order').text('Enter a valid order.');
                                    $('#txtOrder').addClass("border-red");
                                    valid = false;
                                } else {
                                    $('.msg-order').text('');
                                    $('#txtOrder').removeClass("border-red");
                                }
                                if( ! valid ) event.preventDefault();
                                if( valid ) {
                                    $('#sbmEmployee').prop('disabled', true);
                                }
                            });
                        })
                    </script>
                </form>
            </div>
        </div>
    </div>
</div>
