<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Subscribe Email Detail </h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <h3>Information:</h3>
                <table class="table table-hover table-striped table-responsive table-bordered table-activity">
                    <tbody>
                    <tr>
                        <td>Subscribe Email</td>
                        <td><?php echo $arr_newletter['newletter']->newletter_email; ?></td>
                    </tr>
                    <tr>
                        <td>Subscribe IP</td>
                        <td><?php echo $arr_newletter['newletter']->newletter_ip; ?></td>
                    </tr>
                    <tr>
                        <td>Insert Time</td>
                        <td><?php echo date('M/d/Y - H:i:s', $this->my->localTime($arr_newletter['newletter']->newletter_insert_time)); ?></td>
                    </tr>
                    </tbody>
                </table>

                <?php if (count($arr_newletter['location_info']) > 0) { ?>
                    <h3>Location Information:</h3>
                    <table class="table table-hover table-striped table-responsive table-bordered table-activity">
                        <tbody>
                        <tr>
                            <td style="width: 250px" >IP Address</td>
                            <td><?php echo $arr_newletter['location_info']['ip_address']; ?></td>
                        </tr>
                        <tr>
                            <td>Location</td>
                            <td><?php echo $arr_newletter['location_info']['location']; ?></td>
                        </tr>
                        </tbody>
                    </table>
                <?php } ?>
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-1">
                    <a class="btn btn-primary" href="<?php echo $this->url->get("/dashboard/list-newletter"); ?>">Back List</a>
                </div>
            </div>
        </div>
    </div>
</div>

