<script>
    $(document).ready(function () {

        var id = <?php echo $oldinput["id"]; ?>;
        $('#txtName').on('input', function () {
            var str = $(this).val();
            $('#txDesc').val(str);
        });
        $('form[name=type-form]').submit(function (event) {
            var valid = true;
            if ($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if ($('input[name=txtInsertTime]').val() == '') {
                $('.msg-time').text('Insert Time field is required.');
                $('#txtInsertTime').addClass("border-red");
                valid = false;
            } else {
                $('.msg-time').text('');
                $('#txtInsertTime').removeClass("border-red");
            }
            if ($('textarea[name=txtDesc]').val() == '') {
                $('.msg-description').text('Description field is required.');
                $('#txtDesc').addClass("border-red");
                valid = false;
            } else {
                $('.msg-description').text('');
                $('#txtDesc').removeClass("border-red");
            }
            if ($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if (!valid) event.preventDefault();
            if (valid) {
                $('button[name=sbmType]').prop('disabled', true);
            }
        });
    });

</script>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Album Image <?php echo \Bincg\Repositories\Album::getNameByID($album_id) ;?></h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Create
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br/>
                <form name="type-form" id="type-form" data-parsley-validate class="form-horizontal form-label-left"
                      method="post">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Order <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($oldinput["order"]) ? $oldinput["order"] : "" ?>"
                                   id="txtOrder" name="txtOrder"
                                   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["order"])) ? $messages["status"] : ""; ?>"
                                   type="text">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Icon </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($oldinput["icon"]) ? $oldinput["icon"] : "" ?>" id="txtIcon"
                                   name="txtIcon"
                                   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["icon"])) ? $messages["status"] : ""; ?>"
                                   type="text">
                            <span class="text-danger msg-icon"><?php echo isset($messages["icon"]) ? $messages["icon"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Description <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtDesc" name="txtDesc"
                                      style="height: 212px;"><?php echo isset($oldinput["description"]) ? $oldinput["description"] : ""; ?></textarea>
                            <span class="text-danger msg-description"><?php echo isset($messages["description"]) ? $messages["description"] : "" ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Insert Time <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input value="<?php echo isset($oldinput["insert_time"]) ? $oldinput["insert_time"] : "" ?>"
                                   type="text" id="txtInsertTime" name="txtInsertTime"
                                   class="form-control col-md-7 col-xs-12 <?php echo isset($messages["insert_time"]) ? $messages["status"] : ""; ?>">MM/DD/YYYY
                            H:M:S<br>
                            <span class="text-danger msg-time"><?php echo isset($messages["insert_time"]) ? $messages["insert_time"] : "" ?></span>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmType" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary"
                               href="<?php echo $this->url->get("/dashboard/list-image?album_id=" . $album_id); ?>">Cancel</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
