<?php

/**
 * @var $lang_url;
 * @var $lang_code;
 * @var $lang_url_slashed;
 * @var \Score\Models\ScArticle[] $service_articles
 * @var \Score\Models\ScArticle[] $new_articles
 */
$repoType = new \Score\Repositories\Type();
?>
<main>
    <div class="container">
        <h2 class="text-center">
            Tỷ số, lịch thi đấu và kết quả bóng đá trực tiếp
        </h2>
        <div class="form">
            <div class="form-live form-item">
                <input type="checkbox" id="live" class="checkbox-input" name="live" />
                <label for="live" class="checkbox-label"></label>
                <span>Trực tiếp</span>
            </div>
            <div class="form-search">
                <input type="text" placeholder="Tìm kiếm các trận đấu" />
            </div>
            <div class="form-calendar form-item">
                <input type="text" class="form-calendar-input" placeholder="Chọn ngày" />
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container body">
            <?=  $html_tournament ?>
        </div>
    </section>
</main>


<script>
    setInterval(function() {
        $.ajax({
            url: "<?php echo $this->url->get('/'); ?>",
            type: 'GET',
            success: function(data) {
                var getData = JSON.parse(data);
                $(".body").html(getData);
                console.log(123);
            }
        });
    }, 2000);
</script>