<?php
/**
 * @var $lang_url;
 * @var $lang_code;
 * @var $lang_url_slashed;
 * @var \Bincg\Models\BinArticle[] $service_articles
 * @var \Bincg\Models\BinArticle[] $new_articles
 * @var \Bincg\Models\BinCareer[] $career_articles
 */
$repoType = new \Bincg\Repositories\Type();
?>
<?php $this->view->partial('shared/layoutbanner'); ?>
<?php echo defined('txt_home_content_about_us') ? str_replace('|||LANG|||',$lang_url_slashed,txt_home_content_about_us) : ''; ?>
<?php if(count($service_articles)>0){ ?>
    <div class="padding-block">
        <div class="container">
            <h1 class="text-center text-main title-mark"><?php echo defined('txt_what_we_do') ? txt_what_we_do : ''; ?></h1>
            <div class="row">
                <?php foreach ($service_articles as $key => $service_article){
                    $style_id = $key%3+1;
                    ?>
                    <div class="col-md-4">
                        <a class="special-hover-card style-<?php echo $style_id; ?>" href="<?php echo $this->url->get($lang_url.'/services/'.$service_article->getArticleKeyword()); ?>" title="<?php echo strip_tags($service_article->getArticleName()); ?>" target="_self">
                            <div class="image">
                                <img class="full lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $service_article->getArticleIcon(); ?>" alt="<?php echo strip_tags($service_article->getArticleName()); ?>" title="<?php echo strip_tags($service_article->getArticleName()); ?>" />
                                <div class="hover-title">
                                    <p>
                                        <?php echo $service_article->getArticleSummary(); ?>
                                    </p>
                                    <span>
                                        <?php echo defined('btn_learn_more') ? btn_learn_more : ''; ?>
                                        <img class="pl-1 lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $this->url->getStatic('frontend/'); ?>images/icon-arrow-right.svg" alt="<?php echo strip_tags($service_article->getArticleName()); ?>" title="<?php echo strip_tags($service_article->getArticleName()); ?>" />
                                    </span>
                                </div>
                            </div>
                            <div class="content">
                                <div class="content-img">
                                    <img class="lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $service_article->getArticleLogo(); ?>" alt="<?php echo strip_tags($service_article->getArticleName()); ?>" title="<?php echo strip_tags($service_article->getArticleName()); ?>" />
                                    <img class="hover-image lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $service_article->getArticleLogoActive(); ?>" alt="<?php echo strip_tags($service_article->getArticleName()); ?>" title="<?php echo strip_tags($service_article->getArticleName()); ?>" />
                                </div>
                                <h3><?php echo $service_article->getArticleName(); ?></h3>
                            </div>
                        </a>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
<?php } ?>
<?php echo defined('txt_home_content_brand_info') ? str_replace('|||LANG|||',$lang_url_slashed,txt_home_content_brand_info) : ''; ?>
<?php if(count($new_articles)>0){ ?>
    <div class="padding-block">
        <div class="container">
            <h2 class="text-main title-mark text-32"><?php echo defined('txt_news') ? txt_news : ''; ?></h2>
            <div class="row">
                <?php foreach ($new_articles as $key=>$article){
                    $type_by_id = $repoType->getTypeById($article->getArticleTypeId(),$lang_code);
                    $type_key_by_id = $type_by_id ? $type_by_id->getTypeKeyword() : '';
                    if($key==0){
                    ?>
                <div class="col-lg-6">
                    <a class="box-decor-content-wrapper" href="<?php echo $this->url->get($lang_url.'/news/'.$article->getArticleKeyword()); ?>" target="_self" title="<?php echo strip_tags($article->getArticleName()); ?>">
                        <?php if(!$isMobile){ ?>
                            <img class="full lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $article->getArticleMetaImage(); ?>" alt="<?php echo strip_tags($article->getArticleName()); ?>" title="<?php echo strip_tags($article->getArticleName()); ?>">
                        <?php }else{ ?>
                            <img class="full lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $article->getArticleMetaImage(); ?>" alt="<?php echo strip_tags($article->getArticleName()); ?>" title="<?php echo strip_tags($article->getArticleName()); ?>">
                        <?php } ?>
                        <div class="box-decor-content w-100">
                            <p class="text-14"><?php echo $this->my->formatTimeAr($article->getArticleInsertTime()); ?></p>
                            <h3 class="text-normal text-white"><?php echo $article->getArticleName(); ?></h3>
                            <p><u><?php echo defined('btn_read_more') ? btn_read_more : ''; ?></u></p>
                        </div>
                    </a>
                </div>
                <?php }} ?>
                <?php if(count($new_articles)>1){ ?>
                <div class="col-lg-6 mt-4 mt-md-0">
                    <?php foreach ($new_articles as $key=>$article){
                        $type_by_id = $repoType->getTypeById($article->getArticleTypeId(),$lang_code);
                        $type_key_by_id = $type_by_id ? $type_by_id->getTypeKeyword() : '';
                        if($key!=0){
                        ?>
                        <div class="media">
                            <a href="<?php echo $this->url->get($lang_url.'/news/'.$article->getArticleKeyword()); ?>" class="mr-3" target="_self" title="<?php echo strip_tags($article->getArticleName()); ?>">
                                <img class="lazyload" <?php echo $isMobile ? 'width="130"' : 'width="200"'; ?> src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $article->getArticleIcon(); ?>" alt="<?php echo strip_tags($article->getArticleName()); ?>" title="<?php echo strip_tags($article->getArticleName()); ?>">
                            </a>
                            <div class="media-body">
                                <p class="text-gray-date"><?php echo $this->my->formatTimeAr($article->getArticleInsertTime()); ?></p>
                                <h3>
                                    <a href="<?php echo $this->url->get($lang_url.'/news/'.$article->getArticleKeyword()); ?>" target="_self" title="<?php echo strip_tags($article->getArticleName()); ?>">
                                        <?php echo $article->getArticleName(); ?>
                                    </a>
                                </h3>
                                <a class="text-blue text-underline" href="<?php echo $this->url->get($lang_url.'/news/'.$article->getArticleKeyword()); ?>" target="_self" title="<?php echo strip_tags($article->getArticleName()); ?>">
                                    <?php echo defined('btn_read_more') ? btn_read_more : ''; ?>
                                </a>
                            </div>
                        </div>
                    <?php }} ?>
                </div>
                <?php } ?>

            </div>
        </div>
    </div>
<?php } ?>
<?php if(count($career_articles)>0){
    $repoOffice = new \Bincg\Repositories\Office();
    ?>
    <div class="padding-block">
        <div class="container">
            <h2 class="text-main title-mark text-32">
                <?php echo defined('txt_careers') ? txt_careers : ''; ?>
            </h2>
            <div class="p-xs-lr-15">
                <div class="row box-shadow">
                    <?php foreach ($career_articles as $article){
                        $offices = $repoOffice->getAllOfficeByCareerId($article->getCareerId(),$lang_code);
                        ?>
                        <div class="col-lg-3 p-0">
                            <div class="nopadding-card">
                                <h3 class="mb-0">
                                    <a href="<?php echo $this->url->get($lang_url.'/careers/'.$article->getCareerKeyword()); ?>" target="_self" title="<?php echo strip_tags($article->getCareerName()); ?>">
                                        <?php echo $article->getCareerName(); ?>
                                    </a>
                                </h3>
                                <p><?php echo $article->getCareerSummary(); ?></p>

                                <div class="box-icon">
                                    <div class="item">
                                        <div class="image">
                                            <img class="lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $this->url->getStatic('frontend/'); ?>images/icon-clock-black.svg" title="<?php echo htmlentities(defined('txt_closing_date') ? txt_closing_date : ''); ?>" alt="<?php echo htmlentities(defined('txt_closing_date') ? txt_closing_date : ''); ?>" />
                                        </div>
                                        <div class="content">
                                            <strong><?php echo defined('txt_closing_date') ? txt_closing_date : ''; ?></strong>
                                            <p><?php echo $this->my->formatDateTo3Month($this->globalVariable->curTime) ?></p>
                                        </div>
                                    </div>
                                    <?php if(count($offices)>0){ ?>
                                        <div class="item">
                                            <div class="image">
                                                <img class="lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $this->url->getStatic('frontend/'); ?>images/icon-location-black.svg" title="<?php echo htmlentities(defined('txt_office_location') ? txt_office_location : ''); ?>" alt="<?php echo htmlentities(defined('txt_office_location') ? txt_office_location : ''); ?>" />
                                            </div>
                                            <div class="content">
                                                <strong><?php echo defined('txt_office_location') ? txt_office_location : ''; ?></strong>
                                                <p>
                                                    <?php foreach ($offices as $office){ ?>
                                                    <span class="text-underline">
                                                        <?php echo \Bincg\Repositories\CountryGeneral::getNameByCode($office->getOfficeCountryCode()); ?>
                                                    </span>
                                                    <?php } ?>
                                                </p>
                                            </div>
                                        </div>
                                    <?php } ?>
                                </div>
                                <a class="text-blue text-underline" href="<?php echo $this->url->get($lang_url.'/careers/'.$article->getCareerKeyword()); ?>" target="_self" title="<?php echo strip_tags($article->getCareerName()); ?>">
                                    <?php echo defined('btn_read_more') ? btn_read_more : ''; ?>
                                </a>
                            </div>
                        </div>
                    <?php } ?>
                    <div class="col-lg-3 p-0">
                        <div class="position-relative">
                            <img class="full lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $this->url->getStatic('frontend/'); ?>images/home-careers.jpg" title="<?php echo htmlentities(defined('btn_view_all') ? btn_view_all : ''); ?>" alt="<?php echo htmlentities(defined('btn_view_all') ? btn_view_all : ''); ?>" />
                            <div class="box-abs">
                                <a class="btn btn-main" href="<?php echo $this->url->get($lang_url.'/careers'); ?>" title="<?php echo htmlentities(defined('btn_view_all') ? btn_view_all : ''); ?>" target="_self">
                                    <?php echo defined('btn_view_all') ? btn_view_all : ''; ?>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>