<?php
$text_schema_contactpoint = defined('txt_schema_global_contactpoint') ? txt_schema_global_contactpoint : '';
$text_schema_social = defined('txt_schema_global_social') ? txt_schema_global_social : '';
if(isset($locationByLoAndLa)) {
    if($locationByLoAndLa){
        if(strlen($locationByLoAndLa->getLocationSchemaContactpoint()) > 0){
            $text_schema_contactpoint = $locationByLoAndLa->getLocationSchemaContactpoint();
        }
        if(strlen($locationByLoAndLa->getLocationSchemaSocial()) > 0){
            $text_schema_social = $locationByLoAndLa->getLocationSchemaSocial();
        }
    }
}
?>

<script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "<?php echo defined('txt_brand_name') ? str_replace('"',"'",txt_brand_name) : ''; ?>",
        "alternateName": "BINCG",
        "url": "<?php echo defined('URL_SITE') ? URL_SITE : '' ?>",
        "logo": "<?php echo defined('schema_logo_png') ? schema_logo_png : '' ?>"
        <?php if(strlen($text_schema_contactpoint)>0){ ?>
            ,
            "contactPoint": [
                <?php echo $text_schema_contactpoint; ?>
            ]
        <?php } ?>
        <?php if(strlen($text_schema_social)>0){ ?>
            ,
            "sameAs": [
                <?php echo $text_schema_social; ?>
            ]
        <?php } ?>
    }
</script>
