<?php foreach ($listMatch as $tournament) :

?>
    <div class="content-item">
        <a href="#" class="content-title">
            <img src="./image/flag-eng.png" alt="country" class="content-country" />
            <h3><?= $tournament['tournament']['name'] ?></h3>
        </a>
        <div class="content-table">
            <?php foreach ($tournament['match'] as $match) : ?>
                <a href="#" class="content-line">
                    <span class="full-time"><?= $match['matchInfo']['time'] ?> </span>
                    <div class="team-club team-left">
                        <h4 class="team-club-name"><?= $match['homeTeam']['name'] ?></h4>
                        <img src="./image/left-team.png" alt="Team" class="team-club-img" />
                    </div>
                    <div class="result">
                        <span><?= $match['homeTeam']['score']['score'] ?></span>
                        <span>-</span>
                        <span><?= $match['awayTeam']['score']['score'] ?></span>
                    </div>
                    <div class="team-club team-right">
                        <img src="./image/right-team.png" alt="Team" class="team-club-img" />
                        <h4 class="team-club-name"><?= $match['awayTeam']['name'] ?></h4>
                    </div>
                </a>
            <?php endforeach ?>

        </div>
    </div>

<?php endforeach ?>