<div class="content-item">
    <a href="#" class="content-title">
        <img src="./image/flag-eng.png" alt="country" class="content-country" />
        <h3>Spain - Copa del Rey</h3>
    </a>
    <div class="content-table">
        <a href="#" class="content-line">
            <span class="full-time">FT</span>
            <div class="team-club team-left">
                <h4 class="team-club-name">Groningen</h4>
                <img src="./image/left-team.png" alt="Team" class="team-club-img" />
            </div>
            <div class="result">
                <span>0</span>
                <span>-</span>
                <span>0</span>
            </div>
            <div class="team-club team-right">
                <img src="./image/right-team.png" alt="Team" class="team-club-img" />
                <h4 class="team-club-name">Groningen</h4>
            </div>
        </a>
        <a href="#" class="content-line">
            <span class="full-time">
                <span class="main-time">90'</span>
                <span class="bonus">+</span>
                <span class="bonus-time">4'</span>
            </span>
            <div class="team-club team-left">
                <h4 class="team-club-name">Groningen</h4>
                <img src="./image/left-team.png" alt="Team" class="team-club-img" />
            </div>
            <div class="result">
                <span>0</span>
                <span>-</span>
                <span>0</span>
            </div>
            <div class="team-club team-right">
                <img src="./image/right-team.png" alt="Team" class="team-club-img" />
                <h4 class="team-club-name">Groningen</h4>
            </div>
        </a>
        <a href="#" class="content-line">
            <span class="full-time"> 23:00 </span>
            <div class="team-club team-left">
                <h4 class="team-club-name">Groningen</h4>
                <img src="./image/left-team.png" alt="Team" class="team-club-img" />
            </div>
            <div class="result">
                <span>0</span>
                <span>-</span>
                <span>0</span>
            </div>
            <div class="team-club team-right">
                <img src="./image/right-team.png" alt="Team" class="team-club-img" />
                <h4 class="team-club-name">Groningen</h4>
            </div>
        </a>
    </div>
</div>