<?php

/**
 * @var $lang_url;
 * @var \Score\Models\ScArticle[] $menu_services
 * @var \Score\Models\ScArticle[] $menu_abouts
 * @var \Score\Models\ScNewspaper[] $footerNewspapers
 */
?>
<?php echo defined('txt_brand_tell_about_us') ? txt_brand_tell_about_us : '' ?>
<?php if (!in_array($this->router->getControllerName(), array('newspapers'))) { ?>
<script>
    commands.push(function () {
        $('.list-cell-white li').on("click", function () {
            $('.list-cell-white li').removeClass('active');
            $(this).addClass('active');
        });
    });
    function loadmore(id){
        $.ajax({
            url: "<?php echo $this->url->get($lang_url."/newspapers/getdata")?>",
            type: 'post',
            data: {id:id},
            success: function(response){
                <?php if(!$isMobile){ ?>
                    $('.newspaper-articles').html(response);
                <?php }else{ ?>
                    $('.newspaper-articles').remove();
                    $('.list-cell-white>li.post_'+id).parent().after(response).show();
                <?php } ?>
            }
        });
    }
</script>

<?php } ?>
<div class="padding-block">
    <div class="container">
       
    </div>

</div>

<link href="<?php echo $this->url->getStatic('shared/'); ?>css/jquery-ui-1.12.1.min.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'" />
<noscript>
    <link rel="stylesheet" href="<?php echo $this->url->getStatic('shared/'); ?>css/jquery-ui-1.12.1.min.css" type="text/css" media="screen" />
</noscript>
<link href="<?php echo $this->url->getStatic('frontend/'); ?>css/app-critical-1.3.min.css" rel="stylesheet">
<link href="<?php echo $this->url->getStatic('frontend/'); ?>css/app.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript>
    <link rel="stylesheet" href="<?php echo $this->url->getStatic('frontend/'); ?>css/app.css">
</noscript>
<?php if (in_array($this->router->getControllerName(), array('index', 'applycv', 'careers', 'contactus'))) { ?>
    <link href="<?php echo $this->url->getStatic('frontend/'); ?>css/intlTelInput.min.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link href="<?php echo $this->url->getStatic('frontend/'); ?>css/intlTelInput.min.css" rel="stylesheet">
    </noscript>

<?php } ?>
<?php if (in_array($this->router->getControllerName(), array('index', 'applycv', 'careers', 'contactus'))) { ?>
    <link href="<?php echo $this->url->getStatic('frontend/'); ?>js/select2/select2-1.0.min.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'" />
    <noscript>
        <link rel="stylesheet" href="<?php echo $this->url->getStatic('frontend/'); ?>js/select2/select2-1.0.min.css" />
    </noscript>

<?php } ?>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/jquery-3.5.1.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/popper.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/bootstrap-4.5.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/lazysizes.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/ls.bgset.min.js"></script>
<script src="<?php echo $this->url->getStatic('shared/'); ?>js/jquery-ui-1.12.1.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/style-1.1.min.js"></script>
<script>
    document.addEventListener('lazybeforeunveil', function(e) {
        var bg = e.target.getAttribute('data-bgset');
        if (bg) {
            e.target.style.backgroundImage = 'url(' + bg + ')';
        }
    });
</script>

</body>

</html>