<?php

/**
 * @var $lang_url;
 * @var \Bincg\Models\BinArticle[] $menu_services
 * @var \Bincg\Models\BinArticle[] $menu_abouts
 * @var \Bincg\Models\BinNewspaper[] $footerNewspapers
 */
?>
<?php echo defined('txt_brand_tell_about_us') ? txt_brand_tell_about_us : '' ?>
<?php if (!in_array($this->router->getControllerName(), array('newspapers'))) { ?>
<script>
    commands.push(function () {
        $('.list-cell-white li').on("click", function () {
            $('.list-cell-white li').removeClass('active');
            $(this).addClass('active');
        });
    });
    function loadmore(id){
        $.ajax({
            url: "<?php echo $this->url->get($lang_url."/newspapers/getdata")?>",
            type: 'post',
            data: {id:id},
            success: function(response){
                <?php if(!$isMobile){ ?>
                    $('.newspaper-articles').html(response);
                <?php }else{ ?>
                    $('.newspaper-articles').remove();
                    $('.list-cell-white>li.post_'+id).parent().after(response).show();
                <?php } ?>
            }
        });
    }
</script>
<?php if(count($footerNewspapers) >0) { ?>
    <div class="padding-block">
        <div class="container">
            <h2 class="mb-lg-4"><?php echo defined('txt_footer_newspaper_title') ? txt_footer_newspaper_title : '' ?></h2>
            <?php if(!$isMobile){ ?>
                <ul class="list-cell-white text-center">
                    <?php foreach ($footerNewspapers as $footerNewspaper){ ?>
                        <li onclick="loadmore(<?php echo $footerNewspaper->getNewspaperId();?>,true);">
                            <img src="<?php echo $footerNewspaper->getNewspaperLogo(); ?>" alt="<?php echo $footerNewspaper->getNewspaperName(); ?>" title="<?php echo $footerNewspaper->getNewspaperName(); ?>">
                        </li>
                    <?php } ?>
                </ul>
                <div class="newspaper-articles"></div>
            <?php }else{ ?>
                    <?php $footerNewspaperI=0; $itemPerBlock=2; foreach ($footerNewspapers as $footerNewspaperKey => $footerNewspaper){
                        $footerNewspaperI++;
                        if($footerNewspaperI%$itemPerBlock == 1){ ?>
                            <ul class="list-cell-white text-center">
                        <?php } ?>
                                <li class="post_<?php echo $footerNewspaper->getNewspaperId() ?>" onclick="loadmore(<?php echo $footerNewspaper->getNewspaperId();?>,true);">
                                    <img src="<?php echo $footerNewspaper->getNewspaperLogo(); ?>" alt="<?php echo $footerNewspaper->getNewspaperName(); ?>" title="<?php echo $footerNewspaper->getNewspaperName(); ?>">
                                </li>
                        <?php if($footerNewspaperI%$itemPerBlock == 0 || $footerNewspaperI == count($footerNewspapers)){ ?>
                            </ul>
                        <?php } ?>
                    <?php } ?>

            <?php } ?>
            <div class="text-center <?php echo $isMobile ? ' mt-20' : ' mt-40' ?>">
                <a href="<?php echo $this->url->get($lang_url.'/newspapers'); ?>" class="btn btn-main" target="_self" title="<?php echo defined('btn_view_all') ? btn_view_all : '' ?>"><?php echo defined('btn_view_all') ? btn_view_all : '' ?></a>
            </div>
        </div>
    </div>
<?php } ?>
<?php } ?>
<div class="padding-block">
    <div class="container">
        <?php if ($locationByLoAndLa) {
            echo $locationByLoAndLa->getLocationNewspaperstalk();
        } ?>
    </div>

</div>
<div class="footer-address">
    <div class="container">
        <div class="row d-md-flex flex-row-reverse">
            <div class="col-md-6 mb-2">
                <div class="row">
                    <div class="col-6">
                        <h3 class="text-uppercase">
                            <a href="<?php echo $this->url->get($lang_url . '/services'); ?>" target="_self" title="<?php echo htmlentities(defined('txt_what_we_do') ? txt_what_we_do : ''); ?>">
                                <?php echo defined('txt_what_we_do') ? txt_what_we_do : ''; ?>
                            </a>
                        </h3>
                        <?php if (count($menu_services) > 0) { ?>
                            <ul>
                                <?php foreach ($menu_services as $menu_service) { ?>
                                    <li>
                                        <a href="<?php echo $this->url->get($lang_url . '/services/' . $menu_service->getArticleKeyword()); ?>" target="_self" title="<?php echo strip_tags($menu_service->getArticleName()); ?>">
                                            <?php echo $menu_service->getArticleName(); ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        <?php } ?>
                    </div>
                    <div class="col-6">
                        <h3 class="text-uppercase">
                            <a href="<?php echo $this->url->get($lang_url . '/about-us'); ?>" target="_self" title="<?php echo htmlentities(defined('txt_who_we_are') ? txt_who_we_are : ''); ?>">
                                <?php echo defined('txt_who_we_are') ? txt_who_we_are : ''; ?>
                            </a>
                        </h3>
                        <?php if (count($menu_abouts) > 0) { ?>
                            <ul>
                                <?php foreach ($menu_abouts as $menu_about) { ?>
                                    <li>
                                        <a href="<?php echo $this->url->get($lang_url . '/about-us#' . $menu_about->getArticleKeyword()); ?>" target="_self" title="<?php echo strip_tags($menu_about->getArticleName()); ?>">
                                            <?php echo $menu_about->getArticleName(); ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        <?php } ?>
                        <h3 class="text-uppercase">
                            <?php echo defined('txt_information') ? txt_information : ''; ?>
                        </h3>
                        <ul>
                            <li>
                                <a href="<?php echo $this->url->get($lang_url . '/contact-us'); ?>" target="_self" title="<?php echo htmlentities(defined('txt_contact_us') ? txt_contact_us : ''); ?>">
                                    <?php echo defined('txt_contact_us') ? txt_contact_us : ''; ?>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get($lang_url . '/careers'); ?>" target="_self" title="<?php echo htmlentities(defined('txt_careers') ? txt_careers : ''); ?>">
                                    <?php echo defined('txt_careers') ? txt_careers : ''; ?>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get($lang_url . '/corporate-social-responsibility'); ?>" target="_self" title="<?php echo htmlentities(defined('txt_corporate_social_responsibility') ? txt_corporate_social_responsibility : ''); ?>">
                                    <?php echo defined('txt_corporate_social_responsibility') ? txt_corporate_social_responsibility : ''; ?>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get($lang_url . '/news'); ?>" target="_self" title="<?php echo htmlentities(defined('txt_news') ? txt_news : ''); ?>">
                                    <?php echo defined('txt_news') ? txt_news : ''; ?>
                                </a>
                            </li>
                            <?php /* ?>
                            <li>
                                <a href="<?php echo $this->url->get($lang_url.'/events-photos'); ?>" target="_self" title="<?php echo htmlentities(defined('txt_events_photos') ? txt_events_photos : ''); ?>">
                                    <?php echo defined('txt_events_photos') ? txt_events_photos : ''; ?>
                                </a>
                            </li>
                            <?php */ ?>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <h2 class="text-main mb-3">
                    <?php echo defined('txt_brand_name') ? str_replace('|||LANG|||', $lang_url_slashed, txt_brand_name) : ''; ?>
                </h2>
                <?php echo defined('txt_footer_address') ? str_replace('|||LANG|||', $lang_url_slashed, txt_footer_address) : ''; ?>
            </div>
        </div>
    </div>
</div>
<div class="footer-social">
    <div class="container">
        <div class="row d-md-flex flex-row-reverse">
            <div class="col-md-6 mb-4 mb-md-0">
                <div class="flex-md-center">
                    <div>
                        <?php echo defined('txt_social') ? str_replace('|||LANG|||', $lang_url_slashed, txt_social) : ''; ?>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-md-0 mb-3">
                <h3 class="text-uppercase">
                    <?php echo defined('txt_subscribe_us') ? txt_subscribe_us : ''; ?>
                </h3>
                <form id="frmRegisMail">
                    <div class="input-button-group">
                        <input type="text" name="rgs_mail" id="rgs_mail" class="form-control" placeholder="<?php echo htmlentities(defined('txt_please_type_email') ? txt_please_type_email : ''); ?>">
                        <button form="frmRegisMail" type="submit" class="btn btn-main text-uppercase text-nowrap">
                            <?php echo defined('btn_subscribe') ? btn_subscribe : ''; ?>
                        </button>
                    </div>
                    <p id="email_msg" class="mt-3 text-danger"></p>
                </form>
                <script>
                    commands.push(function() {
                        var loginEmail = $("#rgs_mail");
                        var emaiError = $("#email_msg");
                        $("#frmRegisMail").submit(function(event) {
                            event.preventDefault();
                            validEmail = true;
                            if (loginEmail.prop("value").length < 1) {
                                emaiError.text("<?php echo defined('txt_enter_email') ? txt_enter_email : '' ?>");
                                loginEmail.focus();
                                validEmail = false;
                            } else {
                                emaiError.text("");
                            }
                            if (!validEmail) {
                                event.preventDefault();
                            } else {
                                loginEmail.prop("disabled", true);
                                var recapchaSiteKeyV3 = "<?= defined('RECAPTCHA_SITEKEY_V3') ? RECAPTCHA_SITEKEY_V3 : '' ?>";
                                grecaptcha.ready(function() {
                                    grecaptcha.execute(recapchaSiteKeyV3, {
                                            action: 'validate_captcha'
                                        })
                                        .then(function(token) {
                                            $('#frmRegisMail').prepend('<input type="hidden" name="g-recaptcha-response" value="' + token + '">');
                                            $.ajax({
                                                method: "POST",
                                                dataType: "json",
                                                data: {
                                                    rgs_mail: loginEmail.prop("value"),
                                                    token: token
                                                },
                                                url: "<?php echo $this->url->get($lang_url . '/newsletter'); ?>",
                                                cache: false,
                                                success: function(data) {
                                                    emaiError.text(data.msg);
                                                    loginEmail.prop("disabled", false);
                                                    loginEmail.val("");
                                                },
                                                error: function(e) {}
                                            });
                                        });
                                });

                            }
                            return false;
                        });
                    })
                </script>
            </div>
        </div>
    </div>
</div>
<?php
$link_open = 'onclick="window.open';
echo $isMobile && defined('txt_footer_support') ? str_replace('|||WINDOWOPENFIRST|||', $link_open, txt_footer_support) : '';
?>
<div class="footer-contain">
    <div class="container text-center">
        <?php echo defined('txt_footer_copyright') ? str_replace('|||YEAR|||', date('Y', $this->globalVariable->curTime), txt_footer_copyright) : ''; ?>
    </div>
</div>
<div id="l-loading" style="position: fixed;z-index: 10000;top: 0;left: 0;width: 100%;height: 100%;filter: alpha(opacity=85);opacity: 1;text-align: center;display:none;">
    <div style="background-color: rgba(255, 255, 255, 0.9);width: 100%;height: 100%;">
        <img src="<?php echo $this->url->getStatic('frontend/images/waiting.gif'); ?>" alt='<?php echo htmlentities(defined('txt_processing') ? txt_processing : ''); ?>' title='<?php echo htmlentities(defined('txt_processing') ? txt_processing : ''); ?>' style="vertical-align:middle;position: relative;z-index: 10001;top: calc(50% - 16px)">
    </div>
</div>
<?php if (in_array($this->router->getControllerName(), array('applycv', 'careers'))) { ?>
    <?php $this->partial('shared/applycv'); ?>
<?php } ?>
<link href="<?php echo $this->url->getStatic('shared/'); ?>css/jquery-ui-1.12.1.min.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'" />
<noscript>
    <link rel="stylesheet" href="<?php echo $this->url->getStatic('shared/'); ?>css/jquery-ui-1.12.1.min.css" type="text/css" media="screen" />
</noscript>
<link href="<?php echo $this->url->getStatic('frontend/'); ?>css/app-critical-1.3.min.css" rel="stylesheet">
<link href="<?php echo $this->url->getStatic('frontend/'); ?>css/app-2.5.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript>
    <link rel="stylesheet" href="<?php echo $this->url->getStatic('frontend/'); ?>css/app-2.5.css">
</noscript>
<?php if (in_array($this->router->getControllerName(), array('index', 'applycv', 'careers', 'contactus'))) { ?>
    <link href="<?php echo $this->url->getStatic('frontend/'); ?>css/intlTelInput.min.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link href="<?php echo $this->url->getStatic('frontend/'); ?>css/intlTelInput.min.css" rel="stylesheet">
    </noscript>

<?php } ?>
<?php if (in_array($this->router->getControllerName(), array('index', 'applycv', 'careers', 'contactus'))) { ?>
    <link href="<?php echo $this->url->getStatic('frontend/'); ?>js/select2/select2-1.0.min.css" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'" />
    <noscript>
        <link rel="stylesheet" href="<?php echo $this->url->getStatic('frontend/'); ?>js/select2/select2-1.0.min.css" />
    </noscript>

<?php } ?>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/jquery-3.5.1.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/popper.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/bootstrap-4.5.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/lazysizes.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/ls.bgset.min.js"></script>
<script src="<?php echo $this->url->getStatic('shared/'); ?>js/jquery-ui-1.12.1.min.js"></script>
<script src="<?php echo $this->url->getStatic('frontend/'); ?>js/style-1.1.min.js"></script>
<script async src="https://www.google.com/recaptcha/api.js?render=<?= defined('RECAPTCHA_SITEKEY_V3') ? RECAPTCHA_SITEKEY_V3 : '' ?>"></script>
<script>
    document.addEventListener('lazybeforeunveil', function(e) {
        var bg = e.target.getAttribute('data-bgset');
        if (bg) {
            e.target.style.backgroundImage = 'url(' + bg + ')';
        }
    });
</script>
<?php if (in_array($this->router->getControllerName(), array('applycv', 'careers', 'contactus'))) { ?>
    <script src="<?php echo $this->url->getStatic('frontend/'); ?>js/intlTelInput.min.js"></script>
<?php } ?>
<?php if (in_array($this->router->getControllerName(), array('applycv', 'careers', 'contactus'))) { ?>
    <script src="<?php echo $this->url->getStatic('frontend/js/knockout-3.5.0.js'); ?>"></script>
    <script src="<?php echo $this->url->getStatic('frontend/js/select2/select2.min.js'); ?>"></script>
    <script async src="https://www.google.com/recaptcha/api.js"></script>
<?php } ?>
<script async>
    for (var __i = 0; __i < commands.length; __i++) {
        commands[__i]();
    }

    if (typeof(dataLayer) === 'object') {
        dataLayer.push({
            'dynx_userIp': '<?php echo $_SERVER['REMOTE_ADDR']; ?>',
            'dynx_location': '<?php echo isset($ipCountryCode) ? $ipCountryCode : ''; ?>',
            'dynx_pagetype': '<?php echo $this->router->getControllerName(); ?>',
            'dynx_platform': '<?php echo $isMobile ? 'mobile' : 'desktop'; ?>',
            'dynx_languageCode': '<?php echo isset($lang_code) ? $lang_code : ''; ?>'
        });
    }
</script>

<?php if (isset($jsSources) && is_array($jsSources)) {
    foreach ($jsSources as $jsSource) { ?>
        <script src="<?php echo $jsSource['src']; ?>"></script>
<?php }
} ?>
</body>

</html>