<?php

/**
 * Local variables
 * @var \Phalcon\Mvc\View\Engine $this
 * @var string $lang_code
 * @var string $lang_url
 * @var \Score\Models\ScArticle[] $menu_services
 * @var \Score\Models\ScArticle[] $menu_corporate_social_responsibility
 * @var \Score\Models\ScArticle[] $menu_abouts
 * @var \Score\Models\ScType[] $news_subtypes
 */
header("X-Frame-Options: SAMEORIGIN");
?>
<!DOCTYPE html>
<html lang="<?php echo $lang_code; ?>">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
      integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css"
    />
    <link rel="stylesheet" href="./frontend/css/app.css" />
    <title>Live Soccer</title>
  </head>

<body>
    <?php if (!in_array($_SERVER['REMOTE_ADDR'], array('127.0.0.1', "::1")) && defined('google_task_manager_body')) {
        echo google_task_manager_body;
    } else { ?>
        <script>
            dataLayer = [];
        </script>
    <?php } ?>
    <?php $controller_name = $this->router->getControllerName(); ?>
    <script>
        var commands = [];
        var WEB_URL = "<?php echo $this->url->get($lang_url . '/'); ?>";
        var txt_please_enter_keyword = '<?php echo defined("txt_please_enter_keyword") ? txt_please_enter_keyword : "" ?>';
    </script>
    <header>
        <div class="container">
          <div class="header">
            <a href="#" class="header-logo">
              <img src="./image/logo.svg" alt="logo" />
            </a>
            <div class="header-nav">
              <a href="#" class="header-nav-item"> livescores </a>
              <a href="#" class="header-nav-item"> Tin nóng </a>
              <a href="#" class="header-nav-item"> chuyển nhượng </a>
              <a href="#" class="header-nav-item"> premier league </a>
            </div>
            <div class="header-toggle">
              <i class="fa fa-bars" aria-hidden="true"></i>
              <i class="fa fa-times" aria-hidden="true"></i>
            </div>
          </div>
        </div>
    </header>
    