<?php
/**
 * @var $lang_code;
 * @var $lang_url_slashed;
 * @var $isMobileOnly;
 * @var $isMobile;
 * @var \Bincg\Models\BinBanner[] $banners
 */
?>
<?php if(count($banners)>0){ ?>
    <div id="sliders" class="carousel slide carousel-fade" data-ride="carousel">
        <?php if(count($banners)>1){ ?>
            <ol class="carousel-indicators">
                <?php for($i = 0; $i < count($banners); $i++){ ?>
                    <li data-target="#sliders" data-slide-to="<?php echo $i; ?>" <?php echo $i==0 ? 'class="active"' : '' ?>></li>
                <?php } ?>
            </ol>
        <?php } ?>
        <div class="carousel-inner">
            <?php foreach ($banners as $keyBanner => $banner){ ?>
            <div class="carousel-item <?php echo $keyBanner == 0 ? 'active' : ''?>">
                <?php if(!$isMobileOnly) { ?>
                    <img class="w-100 lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $banner->getBannerImage(); ?>" alt="<?php echo strip_tags($banner->getBannerTitle()); ?>" title="<?php echo strip_tags($banner->getBannerTitle()); ?>">
                <?php }else{ ?>
                    <img class="w-100 lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $banner->getBannerImageMobile(); ?>" alt="<?php echo strip_tags($banner->getBannerTitle()); ?>" title="<?php echo strip_tags($banner->getBannerTitle()); ?>">
                <?php } ?>
                <?php echo $banner->getBannerContent($lang_url_slashed); ?>
            </div>
            <?php } ?>
        </div>
        <?php if(count($banners)>1){ ?>
            <div class="carousel-controler-wrapper">
                <a class="carousel-control-prev" href="#sliders" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">
                        <?php echo defined('txt_previous') ? txt_previous : ''; ?>
                    </span>
                </a>
                <a class="carousel-control-next" href="#sliders" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">
                        <?php echo defined('txt_next') ? txt_next : ''; ?>
                    </span>
                </a>
            </div>
        <?php } ?>
    </div>
<?php } ?>