<?php
/**
 * @var $lang_url;
 * @var $lang_code;
 * @var $lang_url_slashed;
 * @var $parent_keyword;
 * @var \Bincg\Models\BinArticle[] $articles
 */
?>
<?php if(!$isMobile){ ?>
<div class="breadcrumbs">
    <div class="container">
        <a href="<?php echo $this->url->get($lang_url); ?>" target="_self" title="<?php echo htmlentities(defined('txt_menu_home') ? txt_menu_home : ''); ?>">
            <?php echo defined('txt_menu_home') ? txt_menu_home : '' ?>
        </a>
        <a href="<?php echo $this->url->get($lang_url.'/'.$parent_keyword); ?>" target="_self" title="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>">
            <?php echo isset($menu_bread) ? $menu_bread : '' ?>
        </a>
    </div>
</div>
<?php } ?>
<?php $this->view->partial('shared/layoutbanner'); ?>
<?php echo isset($ar_content) ? $ar_content : ''; ?>

<?php if (count($list_articles) > 0) { ?>
    <div class="padding-block bg-gray2">
        <div class="container">
            <div class="row">
                <?php foreach ($list_articles as $article) { ?>
                    <div class="col-lg-4 mb-4">
                        <a href="<?php echo $this->url->get($lang_url.'/about-us/'.$article->getArticleKeyword()); ?>" title="Corporate Profiles" target="_self"
                           class="position-relative d-inline-block w-100 text-center text-lg-left hover-img">
                            <img class="w-100 lazyload" src="<?php echo $article->getArticleIcon() ?>"
                                 data-src="<?php echo $article->getArticleIcon() ?>"
                                 alt="<?php echo strip_tags($article->getArticleName()) ?>"
                                 title="<?php echo strip_tags($article->getArticleName()) ?>">
                            <div class="box-title-img"><?php echo $article->getArticleName() ?></div>
                        </a>
                    </div>
                <?php } ?>

            </div>
        </div>
    </div>

<?php } ?>

<?php echo defined('txt_worldwide_offices') ? txt_worldwide_offices : '' ?>
