<div class="page-title">
    <div class="title_left">
        <h3>Translate from English</h3>
    </div>
</div>
<style>
    .country_block .container_checkbox {
        padding-left: 27px;
        font-size: 14px;
        line-height: 23px;
    }
</style>
<?php if (isset($msg_result['status'])) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo isset($msg_result['msg']['message_language']) ? $msg_result['msg']['message_language'].'<br>' : ''; ?>
        <?php echo isset($msg_result['msg']['message_table_lang']) ? $msg_result['msg']['message_table_lang'] : ''; ?>
    </div>
<?php } ?>
<?php if(isset($msg_result['arr_translate_error']) && count($msg_result['arr_translate_error']) > 0){ ?>
    <div class="clearfix"></div>
    <div class="alert alert-error alert-dismissible fade in" role="alert">
        Translate error:
        <?php foreach ($msg_result['arr_translate_error'] as $slcTableLangItemKey => $item_translate_error){ ?>
            <br>Table <?php echo $slcTableLangItemKey ?> (<?php echo count($item_translate_error) ?> records)<br>
            <?php foreach ($item_translate_error as $sub_item_translate_error){?>
                - ID = <?php echo $sub_item_translate_error['id'].'('.$sub_item_translate_error['errortext'].')<br> ' ?>
            <?php } ?>
        <?php } ?>
    </div>
<?php } ?>
<?php if(isset($msg_result_all['arr_translate_success'])){ ?>
    <div class="clearfix"></div>
    <div class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $msg_result_all['arr_translate_success'] ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<form class="translate-form" name="translate-form" method="post" action="<?php echo $this->url->get('/dashboard/translate'); ?>">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <h2 class="col-md-12">Translate to Vietnam</h2>
                        <div class="col-md-12 form-group">
                            <button type="button" name="translategeneral" class="btn btn-success">Translate</button>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    function myFunction() {
        setInterval(call, 55000);
    }
    function call(){
        $.ajax({
            url: "<?php echo $this->url->get("/dashboard/translate")?>",
            type: "post",
            success: function(data){
                var getData = JSON.parse(data);
                if(getData.success=='true'){
                    window.location.href = '<?php echo $this->url->get("/dashboard/translate")?>';
                } else{
                    console.log(getData.time_out);
                }
            }
        });
    }
    $(document).ready(function () {
        $("button[name=translategeneral]").click(function (event) {
            var valid = true;


            if( valid ) {
                $('#l-loading').show();
                $('button[name=translategeneral]').prop('disabled', true);
                call();
                myFunction();
            }
        });
    });
</script>
<div class="x_content">
    <div>
        <table class="table table-striped table-bordered">
            <thead class="table_header">
            <tr class="headings">
                <th width="50px" class="column-title">ID</th>
                <th class="column-title">Table</th>
                <th class="column-title">Data</th>
                <th width="160px" class="column-title">Total</th>
                <th class="column-title">Translate from</th>
                <th class="column-title">Translate to</th>
                <th width="160px" class="column-title">Date to run (MM-DD-YYYY<br>H:M:S)</th>
                <th width="70px" class="column-title">Status</th>
                <th width="70px" class="column-title">User</th>
            </tr>
            </thead>
            <tbody class="tb_body">
            <?php
            foreach ($history_translates as $item) {
                ?>
                <tr>
                    <td><?php echo $item->getDetailId(); ?></td>
                    <td><?php echo $item->getDetailTable(); ?></td>
                    <td>
                        <p style="word-break: break-all"><?php echo $item->getDetailData(); ?></p>
                    </td>
                    <td><?php echo $item->getDetailTotal(); ?></td>
                    <td>English</td>
                    <td>
                        <?php $lang_name = \Score\Repositories\Language::getNameByCode($item->getDetailLangCode()); ?>
                        <?php echo $lang_name ? $lang_name : ''; ?>
                    </td>
                    <td><?php echo $this->my->formatDateTime($item->getDetailInsertTime(),false); ?></td>
                    <td class="<?php echo $item->getDetailStatus()=='Success' ? 'text-success' : 'text-danger'; ?>"><?php echo $item->getDetailStatus(); ?></td>
                    <td>
                        <?php
                        $user_translate = \Score\Repositories\User::getFirstUserByUserId($item->getDetailUserId());
                        ?>
                        <?php echo $user_translate ? $user_translate->getUserName().' ['.$user_translate->getUserEmail().']' : ''; ?>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
    <div class="clearfix"></div>
</div>

