<?php
/**
 * @var $lang_url;
 * @var $lang_code;
 * @var $lang_url_slashed;
 * @var $parent_keyword;
 * @var $keyword;
 * @var \Bincg\Models\BinCareer[] $articles
 * @var \Bincg\Models\BinArticle[] $related_articles
 * @var \Bincg\Models\BinArticle[] $general_articles
 * @var \Bincg\Models\BinCareer[] $related_careers
 * @var \Bincg\Models\BinOffice[] $offices
 * @var \Bincg\Models\BinOfficeImage[] $office_images
 */
?>
<?php if(!$isMobile){ ?>
    <div class="breadcrumbs black position-static">
        <div class="container">
            <a href="<?php echo $this->url->get($lang_url); ?>" target="_self" title="<?php echo htmlentities(defined('txt_menu_home') ? txt_menu_home : ''); ?>">
                <?php echo defined('txt_menu_home') ? txt_menu_home : '' ?>
            </a>
            <a href="<?php echo $this->url->get($lang_url.'/'.$parent_keyword); ?>" target="_self" title="<?php echo isset($parent_bread) ? strip_tags($parent_bread) : '' ?>">
                <?php echo isset($parent_bread) ? $parent_bread : '' ?>
            </a>
            <a href="<?php echo $this->url->get($lang_url.'/'.$parent_keyword.'/'.$keyword); ?>" target="_self" title="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>">
                <?php echo isset($menu_bread) ? $menu_bread : '' ?>
            </a>
        </div>
    </div>
<?php } ?>
<div class="padding-block-no-banner">
    <div class="container">
        <h1 class="mt-3 mt-lg-0"><?php echo isset($menu_bread) ? $menu_bread : '' ?></h1>
        <?php if($career){ ?>
        <div class="mb-4">
            <div class="inline-img-text mr-lg-3">
                <img src="<?php echo $this->url->getStatic('frontend/'); ?>images/icon-clock-gray.svg" class="mr-2" alt="<?php echo htmlentities(defined('txt_closing_date') ? txt_closing_date : ''); ?>" title="<?php echo htmlentities(defined('txt_closing_date') ? txt_closing_date : ''); ?>">
                <strong><?php echo defined('txt_closing_date') ? txt_closing_date : ''; ?>: </strong> <span class="text-black pl-1"><?php echo $this->my->formatDateTo3Month($this->globalVariable->curTime) ?></span>
            </div>
            <?php if(count($offices)>0){ ?>
                <div class="inline-img-text mr-lg-3 mb-0">
                    <img src="<?php echo $this->url->getStatic('frontend/'); ?>images/icon-location-gray.svg" class="mr-2" alt="<?php echo htmlentities(defined('txt_office_location') ? txt_office_location : ''); ?>" title="<?php echo htmlentities(defined('txt_office_location') ? txt_office_location : ''); ?>">
                    <strong><?php echo defined('txt_office_location') ? txt_office_location : ''; ?>: </strong>
                    <?php foreach ($offices as $office){ ?>
                    <u class="text-black px-1"><?php echo \Bincg\Repositories\CountryGeneral::getNameByCode($office->getOfficeCountryCode()); ?></u>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
        <?php } ?>
        <div class="pb-5">
            <div class="row">
                <div class="col-lg-8">
                    <div class="content-format">
                        <?php echo isset($ar_content) ? $ar_content : ''; ?>
                    </div>
                    <?php if($career){ ?>
                        <div class="text-center mt-3">
                            <button type="button" data-toggle="modal" data-target="#upLoadCV" onclick="updateModalTitle('<?php echo isset($menu_bread) ? $menu_bread : ''; ?>',<?php echo (int)$career->getCareerId(); ?>)" class="btn btn-main btn-shadow">
                                <?php echo defined('btn_apply_now') ? btn_apply_now : '' ?>
                            </button>
                        </div>
                    <?php } ?>
                    <?php if($article){ ?>
                        <div class="text-center mt-3">
                            <button type="button" data-toggle="modal" data-target="#upLoadCV" onclick="updateModalApplyGeneral()" class="btn btn-main btn-shadow">
                                <?php echo defined('btn_apply_now') ? btn_apply_now : '' ?>
                            </button>
                        </div>
                    <?php } ?>
                </div>
                <div class="col-lg-4 mt-4 mt-lg-0">
                    <?php if($career){$this->view->partial('careers/searchform');} ?>
                    <?php if(count($related_articles)>0){ ?>
                        <div class="mb-5">
                            <?php foreach ($related_articles as $related_article){ ?>
                                <div class="thumb-box-full-img mb-3">
                                    <div class="thumb-box-content">
                                        <h3 class="title"><?php echo $related_article->getArticleName(); ?></h3>
                                        <a class="stretched-link" href="<?php echo $this->url->get($lang_url.'/careers/'.$related_article->getArticleKeyword()); ?>" target="_self" title="<?php echo strip_tags($related_article->getArticleName()); ?>">
                                            <u><?php echo defined('btn_read_more') ? btn_read_more : ''; ?></u>
                                        </a>
                                    </div>
                                    <img class="lazyload" src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg" data-src="<?php echo $related_article->getArticleIcon(); ?>" alt="<?php echo strip_tags($related_article->getArticleName()); ?>" title="<?php echo strip_tags($related_article->getArticleName()); ?>">
                                </div>
                            <?php } ?>
                        </div>
                    <?php } ?>
                    <h2>
                        <?php echo defined('txt_other_recruitment') ? txt_other_recruitment : ''; ?>
                    </h2>
                    <div class="mb-5">
                        <?php foreach ($related_careers as $related_career){ ?>
                        <a class="simple-list" href="<?php echo $this->url->get($lang_url.'/careers/'.$related_career->getCareerKeyword()); ?>" title="<?php echo strip_tags($related_career->getCareerName()); ?>" target="_self">
                            <h3>
                                <?php echo $related_career->getCareerName(); ?>
                            </h3>
                            <p class="text-black text-14">
                                <?php echo $related_career->getCareerSummary(); ?>
                            </p>
                        </a>
                        <?php } ?>
                    </div>
                    <?php if(count($office_images)>0){ ?>
                    <h2><?php echo defined('txt_gallery') ? txt_gallery : ''; ?></h2>
                    <div class="row">
                        <?php foreach ($office_images as $office_image){ ?>
                        <div class="col-6 mb-3 pr-0">
                            <img src="<?php echo $office_image->getImageUrl(); ?>" alt="<?php echo $office_image->getImageUrl(); ?>" title="<?php echo $office_image->getImageUrl(); ?>" class="w-100">
                        </div>
                        <?php } ?>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>

