<?php
/**
 * @var $location_code
 * @var $lang_code
 * @var $lang_url
 * @var Score\Models\ScArticle $article
 * @var Score\Models\ScCareer $career
 */
?>
<?php
$url_site_schema = defined('URL_SITE') ? URL_SITE.'/'.$lang_url : '';
$name_site_schema = defined('txt_brand_name') ? str_replace('"',"'",txt_brand_name) : '';
$logo_site_schema = defined('schema_logo_png') ? schema_logo_png : '';
$text_schema_social = defined('txt_schema_global_social') ? txt_schema_global_social : '';
if(isset($locationByLoAndLa)) {
    if($locationByLoAndLa){
        if(strlen($locationByLoAndLa->getLocationSchemaSocial()) > 0){
            $text_schema_social = $locationByLoAndLa->getLocationSchemaSocial();
        }
    }
}
$href_article_schema = '';
$name_article = '';
if($article){
    $name_article = $this->my->replaceQuotes($article->getArticleName());
    $href_article_schema = $url_site_schema.'/'.$parent_keyword.'/'.$article->getArticleKeyword();
    ?>
    <script type="application/ld+json">
    {
        "@context": "https://schema.org",
	    "@graph": [
	        {
                "@type": "Organization",
                "@id": "<?php echo $href_article_schema; ?>",
                "name": "<?php echo $name_site_schema; ?>",
                "url": "<?php echo $url_site_schema; ?>",
                <?php if(strlen($text_schema_social)>0){ ?>
                    "sameAs": [
                        <?php echo $text_schema_social; ?>
                    ],
                <?php } ?>
                "logo": {
                    "@type": "ImageObject",
                    "@id": "<?php echo $url_site_schema; ?>/#logo",
                    "inLanguage": "<?php echo $lang_code; ?>",
                    "url": "<?php echo $logo_site_schema; ?>",
                    "width": 122,
                    "height": 42,
                    "caption": "<?php echo $name_site_schema; ?>"
                },
                "image": {
                    "@id": "<?php echo $url_site_schema; ?>/#logo"
                }
            },
            {
                "@type": "WebSite",
                "@id": "<?php echo $url_site_schema; ?>/#website",
                "url": "<?php echo $url_site_schema; ?>/",
                "name": "<?php echo $name_site_schema; ?>",
                "inLanguage": "<?php echo $lang_code; ?>",
                "description": "<?php if(isset($meta_descript)) {echo $meta_descript;} ?>",
                "publisher": {
                    "@id": "<?php echo $url_site_schema; ?>/#organization"
                }
            },
            {
                "@type": "ImageObject",
                "@id": "<?php echo $href_article_schema; ?>/#primaryimage",
                "inLanguage": "<?php echo $lang_code; ?>",
                "url": "<?php if(isset($meta_social_image)) {echo $meta_social_image;} ?>",
                "width": 1920,
                "height": 960,
                "caption": "<?php echo $name_article; ?>"
            },
            {
                "@type": "WebPage",
                "@id": "<?php echo $href_article_schema; ?>/#webpage",
                "url": "<?php echo $href_article_schema; ?>",
                "name": "<?php echo $name_article; ?>",
                "isPartOf": {
                    "@id": "<?php echo $url_site_schema; ?>/#website"
                },
                "inLanguage": "<?php echo $lang_code; ?>",
                "primaryImageOfPage": {
                    "@id": "<?php echo $href_article_schema; ?>/#primaryimage"
                },
                "description": "<?php if(isset($meta_descript)) {echo $meta_descript;} ?>"
            }
        ]
    }
</script>
<?php }
if($career){
    $name_article = $career->getCareerName();
    $href_article_schema = $url_site_schema.'/'.$lang_url.'/'.$parent_keyword.'/'.$career->getCareerKeyword();
?>
<script type="application/ld+json">
    {
      "@context" : "https://schema.org/",
      "@type" : "JobPosting",
      "title" : "<?php echo isset($menu_bread) ? $menu_bread : '' ?>",
      "description" : "<?php echo isset($ar_content) ? $this->my->replaceQuotes($ar_content) : '' ?>",
      "skills": "<?php echo $career->getCareerSkill() ?>",
      "experienceRequirements": "<?php echo $career->getCareerExperienceRequirements() ?>",
      "jobBenefits":"<?php echo $career->getCareerJobBenefits() ?>",
      "identifier": {
        "@type": "PropertyValue",
        "name": "<?php echo $name_site_schema ?>",
        "value": ""
      },
      "datePosted" : "<?php echo isset($ar_time) ? $this->my->formatDateYMD($ar_time) : '' ?>",
      "validThrough" : "<?php echo $this->my->formatDateYMDTo3Month($this->globalVariable->curTime) ?>",
      "employmentType" : "<?php echo isset($menu_bread) ? $menu_bread : '' ?>",
      "hiringOrganization" : {
        "@type" : "Organization",
        "name" : "<?php echo $name_site_schema ?>",
        "sameAs" : "<?php echo $url_site_schema; ?>",
        "logo" : "<?php echo defined('schema_logo_png') ? schema_logo_png : ''; ?>"
      },
      "jobLocation": {
      "@type": "Place",
        "address": [
        <?php if(count($offices)>0){
        foreach ($offices as $keyOffice => $office) {
            if ($keyOffice > 0) {echo ',';}
            $officeAddressArr = array();
            $officeAddress = '';
            if (strlen($office->getOfficeAddress()) > 0){
                $officeAddressArr = explode(',', $office->getOfficeAddress());
                $officeAddressArr = array_slice($officeAddressArr,-2);
                $officeAddress = implode(",", $officeAddressArr);
            }
            ?>
            {
                "@type": "PostalAddress",
                "streetAddress": "<?php echo $office->getOfficeAddress(); ?>",
                "addressLocality": "<?php echo $office->getOfficeCountryCode() == 'VN' ? ($lang_code == 'vn' ? 'Quan 7' : 'District 7') : $officeAddress ?>",
                "addressRegion": "<?php echo $officeAddress ?>",
                "postalCode": "<?php echo $office->getOfficePostalCode(); ?>",
                "addressCountry": "<?php echo $office->getOfficeCountryCode(); ?>"
            }
        <?php }} ?>
        ]
      },
     "baseSalary": {<?php echo $career->getCareerBaseSalarySchema() ?>}
    }
</script>
<?php } ?>
