<?php if (!$isMobile) { ?>
    <div class="breadcrumbs">
        <div class="container">
            <a href="<?php echo $this->url->get($lang_url); ?>" target="_self"
               title="<?php echo htmlentities(defined('txt_menu_home') ? txt_menu_home : ''); ?>">
                <?php echo defined('txt_menu_home') ? txt_menu_home : '' ?>
            </a>
            <a href="<?php echo $this->url->get($lang_url . '/' . $parent_keyword); ?>" target="_self"
               title="<?php echo isset($parent_bread) ? strip_tags($parent_bread) : '' ?>">
                <?php echo isset($parent_bread) ? $parent_bread : '' ?>
            </a>
            <a href="<?php echo $this->url->get($lang_url . '/' . $parent_keyword . '/search'); ?>" target="_self"
               title="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>">
                <?php echo isset($menu_bread) ? $menu_bread : '' ?>
            </a>
        </div>
    </div>
<?php } ?>
<?php $this->view->partial('shared/layoutbanner'); ?>
<?php $this->view->partial('careers/searchform'); ?>
<div class="mb-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mx-auto">
                <h2 class="text-black mb-5">
                    <?php echo defined('txt_count_search_result') ? str_replace('|||COUNT|||', count($careers), txt_count_search_result) : ''; ?>
                </h2>
                <div class="row">
                    <?php foreach ($careers as $career) { ?>
                        <a class="col-lg-4 col-6 mb-5"
                           href="<?php echo $this->url->get($lang_url . '/' . $parent_keyword . '/' . $career['career_keyword']); ?>"
                           target="_self" title="<?php echo strip_tags($career['career_name']); ?>">
                            <div class="media media-item">
                                <div class="shadow-icon mr-3">
                                    <?php if (strlen($career['career_icon']) > 0) { ?>
                                        <img class="lazyload"
                                             src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg"
                                             data-src="<?php echo $career['career_icon']; ?>"
                                             alt="<?php echo strip_tags($career['career_name']); ?>"
                                             title="<?php echo strip_tags($career['career_name']); ?>">
                                    <?php } ?>
                                </div>
                                <div class="media-body">
                                    <h3><?php echo $career['career_name']; ?></h3>
                                    <p class="text-grey text-14 m-0"><?php echo $career['career_summary']; ?></p>
                                </div>
                            </div>
                        </a>
                    <?php } ?>
                </div>
                <?php if(count($careers) > 0) {?>
                <div class="text-center d-mobile-flex">
                    <button type="button" data-toggle="modal" data-target="#upLoadCV" onclick="updateModalApplyGeneral()" class="btn btn-main btn-large-width w-mobile-100">
                        <?php echo defined('btn_apply_now') ? btn_apply_now : '' ?>
                    </button>
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>