<div class="page-title">
    <div class="title_left">
        <h3>Azure Search</h3>
    </div>


</div>

<div class="clearfix"></div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <?php
                if($message!=NULL)
                {
                    ?>
                    <p style="font-size:18px;text-align:center" class="alert alert-success">
                        <?php echo $message; ?>
                    </p>
                <?php }	?>
                <?php
                if($messageAlert!=NULL)
                {
                    ?>
                    <p style="font-size:18px;text-align:center" class="alert alert-danger">
                        <?php echo $messageAlert; ?>
                    </p>
                <?php }	?>
                <form class="form-horizontal" id="upload-form" method="post">
                    <div class="form-group">
                        <input type="submit" name="upload_azure" onclick="return confirm('Are you sure you want to upload?');" id="upload_azure" value="Upload Azure" class="btn btn-primary"/>
                        <input type="submit" name="create_azure" onclick="return confirm('Are you sure you want to create?');" id="create_azure" value="Create Azure" class="btn btn-primary"/>
                        <input type="submit" name="delete_azure" onclick="return confirm('Are you sure you want to delete?');" id="delete_azure" value="Delete Azure" class="btn btn-primary"/>
                    </div>
                </form>
                <div class="clearfix"></div>
            </div>

        </div>
    </div>
</div>