<?php
/**
 * @var $lang_url ;
 * @var $parent_keyword ;
 * @var $ar_time ;
 * @var $isMobile ;
 * @var $menu_corporate_social_responsibility ;
 * @var \Score\Models\ScArticle $article
 * @var \Score\Models\ScArticle[] $related_articles
 */
?>
<?php if (!$isMobile) { ?>
    <div class="breadcrumbs black position-static">
        <div class="container">
            <a href="<?php echo $this->url->get($lang_url); ?>" target="_self"
               title="<?php echo htmlentities(defined('txt_menu_home') ? txt_menu_home : ''); ?>">
                <?php echo defined('txt_menu_home') ? txt_menu_home : '' ?>
            </a>
            <a href="<?php echo $this->url->get($lang_url . '/' . $parent_keyword); ?>" target="_self"
               title="<?php echo isset($parent_bread) ? strip_tags($parent_bread) : '' ?>">
                <?php echo isset($parent_bread) ? $parent_bread : '' ?>
            </a>
            <strong>

                <a href="<?php echo $this->url->get($lang_url . '/' . $parent_keyword . '/' . $article->getArticleKeyword()); ?>"
                   target="_self" title="<?php echo strip_tags($article->getArticleKeyword()); ?>">
                    <?php echo $article->getArticleName(); ?>
                </a>
            </strong>

        </div>
    </div>
<?php } ?>
<div class="padding-block-no-banner mb-4 mb-lg-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <h1 class="mt-3 mt-lg-0 line-height-h1"><?php echo isset($menu_bread) ? $menu_bread : '' ?></h1>
                <p class="text-gray-date"><?php echo $this->my->formatTimeArDetail($ar_time); ?></p>
                <div class="content-format">
                    <?php echo isset($ar_content) ? $ar_content : ''; ?>
                </div>

            </div>

            <div class="col-lg-4">
                <?php if(count($related_articles) > 0) { ?>
                    <div class="list-bg-small mb-4">
                        <h2 class="text-18-medium mb-3"><?php echo defined('txt_related_news') ? txt_related_news : ''; ?></h2>
                        <?php foreach ($related_articles as $key => $related_article) { ?>
                            <div class="media mb-3">
                                <a href="<?php echo $this->url->get($lang_url . '/newsroom/' . $related_article->getArticleKeyword()) ?>"
                                   class="mr-3" target="_self"
                                   title="<?php echo strip_tags($related_article->getArticleName()) ?>">
                                    <img class="lazyload" width="130"
                                         src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg"
                                         data-src="<?php echo $related_article->getArticleIcon(); ?>"
                                         alt="<?php strip_tags($related_article->getArticleName()) ?>"
                                         title="<?php strip_tags($related_article->getArticleName()) ?>">
                                </a>
                                <div class="media-body">
                                    <p class="text-gray-date">
                                        <?php echo $this->my->formatTimeArDetail($related_article->getArticleInsertTime()) ?>
                                    </p>
                                    <h3 class="text-black text-16">
                                        <a href="<?php echo $this->url->get($lang_url . '/newsroom/' . $related_article->getArticleKeyword()) ?>"
                                           target="_self">
                                            <?php echo $related_article->getArticleName() ?>
                                        </a>
                                    </h3>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                <?php } ?>

                <?php foreach ($menu_corporate_social_responsibility as $responsibility_item) { ?>
                    <div class="mb-10">
                        <a class="square-box-link bg-gray"
                           href="<?php echo $this->url->get($lang_url . '/corporate-social-responsibility/' . $responsibility_item->getArticleKeyword()); ?>"
                           target="_self"
                           title="<?php echo strip_tags($responsibility_item->getArticleName()); ?>">
                            <?php echo $responsibility_item->getArticleName(); ?>
                        </a>
                    </div>
                <?php } ?>

            </div>

        </div>
    </div>
</div>
