<?php
/**
 * @var $lang_url ;
 * @var $parent_keyword ;
 * @var $isMobile ;
 * @var \Bincg\Models\BinArticle[] $articles
 */
?>
<?php if (!$isMobile) { ?>
    <div class="breadcrumbs black position-static">
        <div class="container">
            <a href="<?php echo $this->url->get($lang_url); ?>" target="_self"
               title="<?php echo htmlentities(defined('txt_menu_home') ? txt_menu_home : ''); ?>">
                <?php echo defined('txt_menu_home') ? txt_menu_home : '' ?>
            </a>
            <a href="<?php echo $this->url->get($lang_url . '/' . $parent_keyword); ?>" target="_self"
               title="<?php echo isset($parent_bread) ? strip_tags($parent_bread) : '' ?>">
                <?php echo isset($parent_bread) ? $parent_bread : '' ?>
            </a>
        </div>
    </div>
<?php } ?>


<div class="padding-block">
    <div class="container">
        <h1 class="text-main title-mark text-32"><?php echo defined('txt_news_room') ? txt_news_room : '' ?></h1>
        <div class="row">
            <?php if (count($articles) > 0) { ?>
                <?php foreach ($articles as $key => $article) { ?>
                    <div class="col-lg-4 mb-30">
                        <a class="news-room-card h-100"
                           href="<?php echo $this->url->get($lang_url . '/' . $parent_keyword . '/' . $article['article_keyword']); ?>"
                           title="<?php echo strip_tags($article['article_name']); ?>" target="_self">
                            <div class="news-room-image">
                                <img class="lazyload"
                                     src="<?php echo $this->url->getStatic('frontend/'); ?>images/sx.svg"
                                     data-src="<?php echo $article['article_icon']; ?>"
                                     alt="<?php echo strip_tags($article['article_name']); ?>"
                                     title="<?php echo strip_tags($article['article_name']); ?>">
                            </div>
                            <div class="news-room-body">
                                <h3 class="mt-10 mb-0"><?php echo $article['article_name']; ?></h3>
                                <p class="m-10 text-small text-gray">
                                    <small>
                                        <?php echo $this->my->formatTimeArDetail($article['article_insert_time']); ?>
                                    </small>
                                </p>
                                <p class="text-justify">
                                    <?php echo $article['article_summary']; ?>
                                </p>
                            </div>
                        </a>
                    </div>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
</div>


<?php if (isset($htmlPaginator) && strlen($htmlPaginator) > 0) { ?>
    <div class="mb-5">
        <?php echo $htmlPaginator; ?>
    </div>
<?php } ?>