<?php
if(isset($role_function)) {
    $pre = 'backend';
    $menu_active = 'class="active"';
    $menu_sub_active = 'style="display: block;"';
    $menu_sub_sub_active = 'class="current-page"';
    $role = new \Bincg\Repositories\Role();
    $controllers = \Bincg\Models\BinRole::getControllers();
    $content = isset($controllers['content']) ? $controllers['content'] : array();
    $check_content = ($role::checkMenu($role_function, $content)) ? true : false;
    $check_content_sub = ($role::checkMenuSub($content, $controllerName)) ? true : false;
    $setting = isset($controllers['setting']) ? $controllers['setting'] : array();
    $check_setting = ($role::checkMenu($role_function, $setting)) ? true : false;
    $check_setting_sub = ($role::checkMenuSub($setting, $controllerName)) ? true : false;

    $translate = isset($controllers['translate']) ? $controllers['translate'] : array();
    $check_translate = ($role::checkMenu($role_function, $translate)) ? true : false;
    $check_translate_sub = ($role::checkMenuSub($translate, $controllerName)) ? true : false;
}
?>
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="<?php echo $this->url->get("/dashboard");?>" class="site_title"><i class="fa fa-institution"></i> <span>BIN Corporation Group </span></a>
        </div>
        <div class="clearfix"></div>
        <br/>
        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <ul class="nav side-menu">
                    <?php if($check_content){ ?>
                        <li <?php echo ($check_content_sub)?$menu_active:""; ?>  ><a><i class="fa fa-database"></i> Content  <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu"  <?php echo ($check_content_sub)?$menu_sub_active:""; ?> >
                                <?php if($role::checkiMenuItem($role_function,"type")) { ?>
                                    <li <?php echo ($controllerName === "type")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/list-type");?>">Type</a>
                                    </li>
                                <?php } ?>

                                <?php if($role::checkiMenuItem($role_function,"newspaper")) { ?>
                                    <li <?php echo ($controllerName === "newspaper")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/list-newspaper");?>">Newspaper</a>
                                    </li>
                                <?php } ?>

                                <?php if($role::checkiMenuItem($role_function,"newspaperarticle")) { ?>
                                    <li <?php echo ($controllerName === "newspaper")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/list-newspaper-article");?>">Newspaper Article</a>
                                    </li>
                                <?php } ?>

                                <?php if($role::checkiMenuItem($role_function,"article")) { ?>
                                    <li <?php echo ($controllerName === "article")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/list-article");?>">Article</a>
                                    </li>
                                <?php } ?>
                                <?php if($role::checkiMenuItem($role_function,"career")) { ?>
                                    <li <?php echo ($controllerName === "career")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/list-career");?>">Career</a>
                                    </li>
                                <?php } ?>
                                <?php if($role::checkiMenuItem($role_function,"album")) { ?>
                                    <li <?php echo ($controllerName === "album")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/list-album");?>">Album</a>
                                    </li>
                                <?php } ?>
                                <?php if($role::checkiMenuItem($role_function,"office")) { ?>
                                <li <?php echo ($controllerName === "office")?$menu_sub_sub_active:""; ?> >
                                    <a href="<?php echo $this->url->get("/dashboard/list-office");?>">Office</a>
                                <?php } ?>

                                    <?php if($role::checkiMenuItem($role_function,"communicationchannel")) { ?>
                                <li <?php echo ($controllerName === "communicationchannel")?$menu_sub_sub_active:""; ?> >
                                    <a href="<?php echo $this->url->get("/dashboard/list-communication-channel");?>">Communication Channel</a>
                                </li>
                            <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>
                    <?php if($check_setting){ ?>
                        <li <?php echo ($check_setting_sub)?$menu_active:""; ?>  ><a><i class="fa fa-sliders"></i> Settings  <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu"  <?php echo ($check_setting_sub)?$menu_sub_active:""; ?> >
                                <?php if($role::checkiMenuItem($role_function,"page")) { ?>
                                    <li <?php echo ($controllerName === "page")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/list-page");?>">Page</a>
                                    </li>
                                <?php } ?>
                                <?php if($role::checkiMenuItem($role_function,"config")) { ?>
                                    <li <?php echo ($controllerName === "config")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/list-config");?>">Config</a>
                                    </li>
                                <?php } ?>
                                <?php if($role::checkiMenuItem($role_function,"banner")) { ?>
                                    <li <?php echo ($controllerName === "banner")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/list-banner");?>">Banner</a>
                                    </li>
                                <?php } ?>
                                <?php if($role::checkiMenuItem($role_function,"emailtemplate")) { ?>
                                    <li <?php echo ($controllerName === "emailtemplate")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/list-emailtemplate");?>">Template Email</a>
                                    </li>
                                <?php } ?>
                                <?php if($role::checkiMenuItem($role_function,"role")) { ?>
                                    <li <?php echo ($controllerName === "role")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/list-role");?>">Role</a>
                                    </li>
                                <?php } ?>
                                <?php if($role::checkiMenuItem($role_function,"language")) { ?>
                                    <li <?php echo ($controllerName === "language")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/list-language");?>">Language</a>
                                    </li>
                                <?php } ?>
                                <?php if($role::checkiMenuItem($role_function,"location")) { ?>
                                    <li <?php echo ($controllerName === "location")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/list-location");?>">Location</a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>
                    <?php if($role::checkiMenuItem($role_function,"cloudupload")) { ?>
                        <li <?php echo ($controllerName == "cloudupload")?$menu_active:""; ?>><a href="<?php echo $this->url->get("/dashboard/cloud-upload");?>"><i class="fa fa-file"></i>Upload File</a></li>
                    <?php } ?>
                    <?php if($role::checkiMenuItem($role_function,"logoupload")) { ?>
                        <li <?php echo ($controllerName == "logoupload")?$menu_active:""; ?>><a href="<?php echo $this->url->get("/dashboard/logo-upload");?>"><i class="fa fa-picture-o"></i>Upload Logo</a></li>
                    <?php } ?>
                    <?php if($role::checkiMenuItem($role_function,"user")) { ?>
                        <li <?php echo ($controllerName == "user")?$menu_active:""; ?>><a href="<?php echo $this->url->get("/dashboard/list-user");?>"><i class="fa fa-user"></i>User</a></li>
                    <?php } ?>
                    <?php if($role::checkiMenuItem($role_function,"contactus")) { ?>
                        <li <?php echo ($controllerName == "contactus")?$menu_active:""; ?>><a href="<?php echo $this->url->get("/dashboard/list-contactus");?>"><i class="fa fa-envelope-o"></i>Contact us</a></li>
                    <?php } ?>
                    <?php if($role::checkiMenuItem($role_function,"apply")) { ?>
                        <li <?php echo ($controllerName == "apply")?$menu_active:""; ?>><a href="<?php echo $this->url->get("/dashboard/list-apply");?>"><i class="fa fa-clipboard"></i>Apply</a></li>
                    <?php } ?>
                    <?php if($role::checkiMenuItem($role_function,"subscribe")) { ?>
                        <li <?php echo ($controllerName === "subscribe")?$menu_active:""; ?> ><a href="<?php echo $this->url->get("/dashboard/list-subscribe");?>"><i class="fa fa-user-md"></i>Subscribe Email</a></li>
                    <?php } ?>
                    <?php if (defined('AZURE_MODE') && AZURE_MODE) {
                        if ($role::checkiMenuItem($role_function, "azuresearch")) { ?>
                            <li <?php echo ($controllerName === "azuresearch") ? $menu_sub_sub_active : ""; ?> >
                                <a href="<?php echo $this->url->get("/dashboard/azure-search"); ?>"><i
                                            class="fa fa-cloud-upload"></i>Azure Search</a>
                            </li>
                        <?php }
                    }?>
                    <?php if($check_translate){ ?>
                        <li <?php echo ($check_translate_sub)?$menu_active:""; ?> ><a><i class="fa fa-language"></i> Translate <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu" <?php echo ($check_translate_sub)?$menu_sub_active:""; ?> >
                                <?php if($role::checkiMenuItem($role_function,"translate")) { ?>
                                    <li <?php echo ($controllerName === "translate" && $actionName === "index")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/translate");?>"> Translate to Vietnam</a>
                                    </li>
                                <?php } ?>

                                <?php if($role::checkiMenuItem($role_function,"tooltranslate")) { ?>
                                    <li <?php echo ($controllerName === "tooltranslate" && $actionName === "index")?$menu_sub_sub_active:""; ?> >
                                        <a href="<?php echo $this->url->get("/dashboard/tool-translate");?>">Tool Translate </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>

                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->
    </div>
</div>