<script>
    $( document ).ready(function() {
        $('form[name=career-form]').submit(function(event) {
            var valid = true;
            if ($('input[name=txtKeyword]').val() == 0) {
                $('.msg-keyword').text('Keyword field is required.');
                $('#txtKeyword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-keyword').text('');
                $('#txtKeyword').removeClass("border-red");
            }
            if($('input[name=txtInsertTime]').val() == '') {
                $('.msg-time').text('Insert time field is required.');
                $('#txtInsertTime').addClass("border-red");
                valid = false;
            } else {
                $('.msg-time').text('');
                $('#txtInsertTime').removeClass("border-red");
            }
            if ($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=sbmCareer]').prop('disabled', true);
            }
        });
        var oFCKeditor2;
        <?php foreach ($formData['arr_language'] as $code => $lang ) { ?>
        oFCKeditor2 = new FCKeditor('txtContent<?php echo $code ?>') ;
        oFCKeditor2.Height = '400';
        oFCKeditor2.Width = '700';
        oFCKeditor2.ToolbarSet = "Default" ;
        oFCKeditor2.Basepath = '../backend/fckeditor/';
        oFCKeditor2.ReplaceTextarea() ;
        <?php } ?>
    });
</script>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Career</h3>
    </div>
</div>
<div class="clearfix"></div>
<?php if(!empty($messages['message']))
{
    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage']?>">
        <?php echo $messages['message']; ?>
    </p>
<?php }	?>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Edit
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form name="career-form" id="career-form" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <input type="hidden" name="save" id="save" value="<?php echo \Bincg\Models\BinLanguage::GENERAL ;?>" />
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Office</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select id="slcOffice" name="slcOffice[]"
                                    class="form-control col-md-7 col-xs-12"
                                    multiple>
                                <?php echo isset($select_office) ? $select_office : '' ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Keyword <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["career_keyword"]) ? $formData["career_keyword"] : "" ?>" id="txtKeyword" name="txtKeyword" class="form-control col-md-7 col-xs-12 <?php echo isset($messages["keyword"]) ? $messages["status"] : ""; ?>" type="text">
                            <span class="text-danger msg-keyword"><?php echo isset($messages["keyword"]) ? $messages["keyword"] : ""?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Insert Time <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input value="<?php echo isset($formData["career_insert_time"]) ?$formData["career_insert_time"] : "" ?>" type="text" id="txtInsertTime" name="txtInsertTime"  class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["career_insert_time"])) ? $messages["status"] : ""; ?>">MM/DD/YYYY H:M:S<br>
                            <span class="text-danger msg-time"><?php echo isset($messages["career_insert_time"]) ? $messages["career_insert_time"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Order <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["career_order"]) ? $formData["career_order"] : "" ?>" id="txtOrder" name="txtOrder" class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["order"])) ? $messages["status"] : ""; ?>" type="text">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : ""; ?></span>
                        </div>
                    </div>
                    <?php if(!empty($select_type)){?>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Services</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <div class="role_block">
                                <div class="well">
                                    <h2 class="text-danger"></h2>
                                    <?php echo $select_type;?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php }?>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Is Home</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radIsHomeActive" value="Y" <?php echo (isset($formData["career_is_home"]) && $formData["career_is_home"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radIsHomeActive" value="N" <?php echo (isset($formData["career_is_home"]) && $formData["career_is_home"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Expired</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radExpired" value="Y" <?php echo (isset($formData["career_expired"]) && $formData["career_expired"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radExpired" value="N" <?php echo (isset($formData["career_expired"]) && $formData["career_expired"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Featured</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radFeatured" value="Y" <?php echo (isset($formData["career_featured"]) && $formData["career_featured"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radFeatured" value="N" <?php echo (isset($formData["career_featured"]) && $formData["career_featured"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Active</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($formData["career_active"]) && $formData["career_active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($formData["career_active"]) && $formData["career_active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>

                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmCareer" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="<?php echo $this->url->get("/dashboard/list-career"); ?>">Cancel</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <ul class="nav nav-pills" role="tablist">
                <?php
                foreach ( $formData['arr_language'] as $code => $lang ){
                $active = $formData['lang_current']== $code?"active":"";
                ?>
                <li role="presentation" class="<?php echo $active; ?>"><a href="#<?php echo $code ?>translate" aria-controls="<?php echo $code ?>translate" role="tab" data-toggle="tab"><?php echo $lang; ?></a></li>
                <?php } ?>
            </ul>
            <div class="tab-content">
                <?php foreach ($formData['arr_language'] as $code => $lang ) {
                $active = $formData['lang_current']== $code?"active":"";
                ?>
                <div role="tabpanel" class="tab-pane <?php echo $active; ?>" id="<?php echo $code; ?>translate">
                    <br>
                    <form name="career-form<?php echo $code; ?>" id="career-form<?php echo $code; ?>" action="" data-parsley-validate class="form-horizontal form-label-left" method="post">
                        <input type="hidden" name="save" id="save" value="<?php echo $code; ?>" />
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtName">Name <span class="text-danger">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["career_name"]) ? $formData['arr_translate'][$code]["career_name"] : "" ?>" type="text" id="txtName<?php echo $code; ?>" name="txtName" class="form-control col-md-7 col-xs-12 <?php echo isset($messages[$code]["name"]) ? $messages["status"] : ""; ?>">
                                <span class="text-danger msg-name-<?php echo $code; ?>"><?php echo isset($messages[$code]["name"]) ? $messages[$code]["name"] : ""?></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="txtTitle" class="control-label col-md-3 col-sm-3 col-xs-12">Title <span class="text-danger">*</span></label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["career_title"]) ? $formData['arr_translate'][$code]["career_title"] : "" ?>" id="txtTitle<?php echo $code; ?>" class="form-control col-md-7 col-xs-12 <?php echo isset($messages[$code]["title"]) ? $messages["status"] : ""; ?>" type="text" name="txtTitle">
                                <span class="text-danger msg-title-<?php echo $code; ?>"><?php echo isset($messages[$code]["title"]) ? $messages[$code]["title"] : ""?></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta keyword <span class="text-danger">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["career_meta_keyword"]) ? $formData['arr_translate'][$code]["career_meta_keyword"] : "" ?>" id="txtMetaKey<?php echo $code; ?>" name="txtMetaKey" class="form-control col-md-7 col-xs-12 <?php echo isset($messages[$code]["meta_keyword"]) ? $messages["status"] : ""; ?>" type="text">
                                <span class="text-danger msg-metakeyword-<?php echo $code; ?>"><?php echo isset($messages[$code]["meta_keyword"]) ? $messages[$code]["meta_keyword"] : ""?></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta description <span class="text-danger">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["career_meta_description"]) ? $formData['arr_translate'][$code]["career_meta_description"] : "" ?>" id="txtMetaDesc<?php echo $code; ?>" name="txtMetaDesc" class="form-control col-md-7 col-xs-12 <?php echo isset($messages[$code]["meta_description"]) ? $messages["status"] : ""; ?>" type="text">
                                <span class="text-danger msg-metadescription-<?php echo $code; ?>"><?php echo isset($messages[$code]["meta_description"]) ? $messages[$code]["meta_description"] : ""?></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Icon</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["career_icon"]) ? $formData['arr_translate'][$code]["career_icon"] : "" ?>" id="txtIcon<?php echo $code; ?>" name="txtIcon" class="form-control col-md-7 col-xs-12" type="text" >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta Image</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input placeholder="1920 x 960" maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["career_meta_image"]) ? $formData['arr_translate'][$code]["career_meta_image"] : "" ?>" id="txtMetaImage<?php echo $code; ?>" name="txtMetaImage" class="form-control col-md-7 col-xs-12" type="text" >
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtLocation<?php echo $code; ?>">Location </label>
                            <div class="col-md-6 col-sm-6 col-xs-12 control-bg">
                                <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["career_location"]) ? $formData['arr_translate'][$code]["career_location"] : "" ?>" id="txtLocation<?php echo $code; ?>" name="txtLocation" class="form-control col-md-7 col-xs-12" type="text">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtSkill">Skill </label>
                            <div class="col-md-6 col-sm-6 col-xs-12 control-bg">
                            <textarea class="form-control" id="txtSkill" name="txtSkill"
                                      style="width: 750px;height: 80px;"><?php echo isset($formData['arr_translate'][$code]["career_skill"]) ? $formData['arr_translate'][$code]["career_skill"] : ""; ?></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtExperience">Experience Requirements </label>
                            <div class="col-md-6 col-sm-6 col-xs-12 control-bg">
                            <textarea class="form-control" id="txtExperience" name="txtExperience"
                                      style="width: 750px;height: 80px;"><?php echo isset($formData['arr_translate'][$code]["career_experience"]) ? $formData['arr_translate'][$code]["career_experience"] : ""; ?></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtJobBenefit">Job Benefits </label>
                            <div class="col-md-6 col-sm-6 col-xs-12 control-bg">
                            <textarea class="form-control" id="txtJobBenefit" name="txtJobBenefit"
                                      style="width: 750px;height: 80px;"><?php echo isset($formData['arr_translate'][$code]["career_job_benefit"]) ? $formData['arr_translate'][$code]["career_job_benefit"] : ""; ?></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtBaseSalary">Base Salary Schema </label>
                            <div class="col-md-6 col-sm-6 col-xs-12 control-bg">
                            <textarea class="form-control" id="txtBaseSalary" name="txtBaseSalary"
                                      style="width: 750px;height: 80px;"><?php echo isset($formData['arr_translate'][$code]["career_base_salary"]) ? $formData['arr_translate'][$code]["career_base_salary"] : ""; ?></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtSummary">Summary </label>
                            <div class="col-md-6 col-sm-6 col-xs-12 control-bg">
                                <textarea class="form-control" id="txtSummary<?php echo $code; ?>" name ="txtSummary" style="width:699px;height: 212px;" ><?php echo isset($formData['arr_translate'][$code]["career_summary"]) ? $formData['arr_translate'][$code]["career_summary"] : ""; ?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtContent">Content</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea class="form-control" id="txtContent<?php echo $code; ?>" name ="txtContent" style="width: 750px;height: 212px;"><?php echo isset($formData['arr_translate'][$code]["career_content"]) ? $formData['arr_translate'][$code]["career_content"] : ""; ?></textarea>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button name="sbmCareer<?php echo $code; ?>" type="submit" class="btn btn-success">Save change</button>
                            </div>
                        </div>
                        <script>
                            $( document ).ready(function() {
                                $('#txtName<?php echo $code; ?>').on('input', function() {
                                    var id = <?php echo isset($formData['arr_translate'][$code]["career_id"]) ? $formData['arr_translate'][$code]["career_id"] : -1;?>;
                                    if(id < 0) {
                                        var str = $(this).val();
                                        $('#txtTitle<?php echo $code; ?>').val(str);
                                        $('#txtMetaKey<?php echo $code; ?>').val(str);
                                        $('#txtMetaDesc<?php echo $code; ?>').val(str);
                                    }
                                });
                                if ($('#txtMetaImage<?php echo $code; ?>').val() == '') {
                                    $('#txtIcon<?php echo $code; ?>').on('input', function() {
                                        var str = $(this).val();
                                        $('#txtMetaImage<?php echo $code; ?>').val(str);

                                    });
                                }
                                $('form[name=career-form<?php echo $code; ?>]').submit(function (event) {
                                    valid = true;
                                    if($('#txtName<?php echo $code; ?>').val() == '') {
                                        valid = false;
                                        $('.msg-name-<?php echo $code;?>').text("Name field is required.");
                                        $('#txtName<?php echo $code; ?>').addClass("border-red");
                                    } else {
                                        $('.msg-name-<?php echo $code;?>').text('');
                                        $('#txtName<?php echo $code; ?>').removeClass("border-red");
                                    }
                                    if($('#txtTitle<?php echo $code; ?>').val() == '') {
                                        $('.msg-title-<?php echo $code; ?>').text('Title field is required.');
                                        $('#txtTitle<?php echo $code; ?>').addClass("border-red");
                                        valid = false;
                                    } else {
                                        $('.msg-title-<?php echo $code; ?>').text('');
                                        $('#txtTitle<?php echo $code; ?>').removeClass("border-red");
                                    }
                                    if($('#txtMetaKey<?php echo $code; ?>').val() == '') {
                                        $('.msg-metakeyword-<?php echo $code; ?>').text('Meta keyword field is required.');
                                        $('#txtMetaKey<?php echo $code; ?>').addClass("border-red");
                                        valid = false;
                                    } else {
                                        $('.msg-metakeyword-<?php echo $code; ?>').text('');
                                        $('#txtMetaKey<?php echo $code; ?>').removeClass("border-red");
                                    }
                                    if($('#txtMetaDesc<?php echo $code; ?>').val() == '') {
                                        $('.msg-metadescription-<?php echo $code; ?>').text('Meta description field is required.');
                                        $('#txtMetaDesc<?php echo $code; ?>').addClass("border-red");
                                        valid = false;
                                    } else {
                                        $('.msg-metadescription-<?php echo $code; ?>').text('');
                                        $('#txtMetaDesc<?php echo $code; ?>').removeClass("border-red");
                                    }
                                    if( ! valid ) event.preventDefault();
                                    if( valid ) {
                                        $('#sbmCareer<?php echo $code; ?>').prop('disabled', true);
                                    }
                                });
                            });
                        </script>
                    </form>
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
