<?php
$urlPage = "?";
if(strlen($this->dispatcher->getParam("txtSearch"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3>Career</h3>
    </div>
</div>
<?php if(isset($msg_result['status'])) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<?php if(isset($msg_delete['success']) && !empty($msg_delete['success'])) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $msg_delete['success']; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<form class="searchForm" name="form-type" method="post">
    <?php $keyword = $this->dispatcher->getParam("txtSearch"); ?>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-1">
                            <h2>Keyword</h2>
                        </div>
                        <div class="col-md-4">
                            <input class="form-control" type="text" name="txtSearch" maxlength="255" placeholder="ID, Name" value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>

                        <div class="col-md-1">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                        </div>
                    </div>
                    <div>
                        <strong>Total</strong>
                        <?php echo count($page); ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                            <?php foreach ($page as $item ) {
                                /**
                                 * @var Offshore\Models\ScCareer $item
                                 */

                                echo "<p class='text-uppercase'><strong><u>[name]</u></strong></p>";
                                echo "<p>".$item->getCareerName()."</p>";

                                echo "<p class='text-uppercase'><strong><u>[title]</u></strong></p>";
                                echo "<p>".$item->getCareerTitle()."</p>";

                                echo "<p class='text-uppercase'><strong><u>[meta keyword]</u></strong></p>";
                                echo "<p>".$item->getCareerMetaKeyword()."</p>";

                                echo "<p class='text-uppercase'><strong><u>[meta description]</u></strong></p>";
                                echo "<p>".$item->getCareerMetaDescription()."</p>";

                                echo "<p class='text-uppercase'><strong><u>[summary]</u></strong></p>";
                                echo "<p>".$item->getCareerSummary() . "</p>";

                                echo "<p class='text-uppercase'><strong><u>[content]</u></strong></p>";
                                echo "<p>".$item->getCareerContent() . "</p>";

                                echo "<hr style='border-top: 3px solid #8c8b8b;'>";
                            }?>

                    <div class="clearfix"></div>

                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function(){
        $('button[name=search]').click(function() {
            $('form[name=form-type]').prop('action','<?php echo $this->url->get('/dashboard/list-career-export'); ?>');
            $('form[name=form-type]').submit();
        });


    });
</script>