<script>
    $( document ).ready(function() {
        $('form[name=type-form]').submit(function(event) {
            var valid = true;
            if($('input[name=txtKeyword]').val() == '') {
                $('.msg-keyword').text('Keyword field is required.');
                $('#txtKeyword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-keyword').text('');
                $('#txtKeyword').removeClass("border-red");
            }
            if ($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=sbmType]').prop('disabled', true);
            }
        });
    });
</script>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Type</h3>
    </div>
</div>
<div class="clearfix"></div>
<?php if(!empty($messages['message']))
{
    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage']?>">
        <?php echo $messages['message']; ?>
    </p>
<?php }	?>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Edit
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form name="type-form" id="type-form" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <input type="hidden" name="save" id="save" value="general" />
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Type  </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select id="slcType" name="txtType" class="form-control col-md-7 col-xs-12" required>
                                <option value=0>Select Type...</option>
                                <?php
                                echo isset($select_type) ? $select_type : "";
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Keyword <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["type_keyword"]) ? $formData["type_keyword"] : "" ?>" id="txtKeyword" name="txtKeyword" class="form-control col-md-7 col-xs-12 <?php echo isset($messages["keyword"]) ? $messages["status"] : ""; ?>" type="text">
                            <span class="text-danger msg-keyword"><?php echo isset($messages["keyword"]) ? $messages["keyword"] : ""?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Order <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="5" value="<?php echo isset($formData["type_order"]) ? $formData["type_order"] : "" ?>" id="txtOrder" name="txtOrder" class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["order"])) ? $messages["status"] : ""; ?>"   type="text">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Active</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($formData["type_active"]) && $formData["type_active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($formData["type_active"]) && $formData["type_active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>

                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button id="sbmType" name="sbmType" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="<?php echo $this->url->get("/dashboard/list-type"); ?>">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <ul class="nav nav-pills" role="tablist">
                <?php
                foreach ( $formData['arr_language'] as $code => $lang ){
                    $active = $formData['lang_current']== $code?"active":"";
                    ?>
                    <li role="presentation" class="<?php echo $active; ?>"><a href="#<?php echo $code ?>translate" aria-controls="<?php echo $code ?>translate" role="tab" data-toggle="tab"><?php echo $lang; ?></a></li>
                <?php } ?>
            </ul>
            <div class="tab-content">
                <?php foreach ($formData['arr_language'] as $code => $lang ) {
                    $active = $formData['lang_current']== $code?"active":"";
                    ?>
                    <div role="tabpanel" class="tab-pane <?php echo $active; ?>" id="<?php echo $code; ?>translate">
                        <br>
                        <form name="type-form<?php echo $code; ?>" id="type-form<?php echo $code; ?>" data-parsley-validate class="form-horizontal form-label-left" method="post">
                            <input type="hidden" name="save" id="save" value="<?php echo $code; ?>" />
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtName">Name <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["type_name"]) ? $formData['arr_translate'][$code]["type_name"] : "" ?>" type="text" id="txtName<?php echo $code; ?>" name="txtName" class="form-control col-md-7 col-xs-12 <?php echo isset($messages[$code]["name"]) ? $messages["status"] : ""; ?>">
                                    <span class="text-danger msg-name-<?php echo $code;?>"><?php echo isset($messages[$code]["name"]) ? $messages[$code]["name"] : ""?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="txtTitle" class="control-label col-md-3 col-sm-3 col-xs-12">Title <span class="text-danger">*</span></label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["type_title"]) ? $formData['arr_translate'][$code]["type_title"] : "" ?>" id="txtTitle<?php echo $code; ?>" class="form-control col-md-7 col-xs-12 <?php echo isset($messages[$code]["title"]) ? $messages["status"] : ""; ?>" type="text" name="txtTitle">
                                    <span class="text-danger msg-title-<?php echo $code;?>"><?php echo isset($messages[$code]["title"]) ? $messages[$code]["title"] : ""?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta keyword <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["type_meta_keyword"]) ? $formData['arr_translate'][$code]["type_meta_keyword"] : "" ?>" id="txtMetaKeyword<?php echo $code; ?>" name="txtMetaKeyword" class="form-control col-md-7 col-xs-12 <?php echo isset($messages[$code]["meta_keyword"]) ? $messages["status"] : ""; ?>" type="text">
                                    <span class="text-danger msg-metakeyword-<?php echo $code;?>"><?php echo isset($messages[$code]["meta_keyword"]) ? $messages[$code]["meta_keyword"] : ""?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta description <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["type_meta_description"]) ? $formData['arr_translate'][$code]["type_meta_description"] : "" ?>" id="txtMetaDescription<?php echo $code; ?>" name="txtMetaDescription" class="form-control col-md-7 col-xs-12 <?php echo isset($messages[$code]["meta_description"]) ? $messages["status"] : ""; ?>" type="text">
                                    <span class="text-danger msg-metadescription-<?php echo $code;?>"><?php echo isset($messages[$code]["meta_description"]) ? $messages[$code]["meta_description"] : ""?></span>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button id="sbmType<?php echo $code; ?>" name="sbmType<?php echo $code; ?>" type="submit" class="btn btn-success">Save change</button>
                                </div>
                            </div>
                            <script>
                                $( document ).ready(function() {
                                    $('#txtName<?php echo $code; ?>').on('input', function() {
                                        var id = <?php echo isset($formData['arr_translate'][$code]["type_id"]) ? $formData['arr_translate'][$code]["type_id"] : -1;?>;
                                        if(id < 0) {
                                            var str = $(this).val();
                                            $('#txtTitle<?php echo $code; ?>').val(str);
                                            $('#txtMetaKeyword<?php echo $code; ?>').val(str);
                                            $('#txtMetaDescription<?php echo $code; ?>').val(str);
                                        }
                                    });
                                    $('form[name=type-form<?php echo $code; ?>]').submit(function (event) {
                                        valid = true;
                                        if($('#txtName<?php echo $code; ?>').val() == '') {
                                            valid = false;
                                            $('.msg-name-<?php echo $code;?>').text("Name field is required.");
                                            $('#txtName<?php echo $code; ?>').addClass("border-red");
                                        } else {
                                            $('.msg-name-<?php echo $code;?>').text('');
                                            $('#txtName<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if($('#txtTitle<?php echo $code; ?>').val() == '') {
                                            $('.msg-title-<?php echo $code; ?>').text('Title field is required.');
                                            $('#txtTitle<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-title-<?php echo $code; ?>').text('');
                                            $('#txtTitle<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if($('#txtMetaKeyword<?php echo $code; ?>').val() == '') {
                                            $('.msg-metakeyword-<?php echo $code; ?>').text('Meta keyword field is required.');
                                            $('#txtMetaKeyword<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-metakeyword-<?php echo $code; ?>').text('');
                                            $('#txtMetaKeyword<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if($('#txtMetaDescription<?php echo $code; ?>').val() == '') {
                                            $('.msg-metadescription-<?php echo $code; ?>').text('Meta description field is required.');
                                            $('#txtMetaDescription<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-metadescription-<?php echo $code; ?>').text('');
                                            $('#txtMetaDescription<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if( ! valid ) event.preventDefault();
                                        if( valid ) {
                                            $('#sbmType<?php echo $code; ?>').prop('disabled', true);
                                        }
                                    });
                                });
                            </script>
                        </form>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

