<?php if(!$isMobile){ ?>
<div class="breadcrumbs black">
    <div class="container">
        <a href="<?php echo $this->url->get($lang_url); ?>" target="_self" title="<?php echo htmlentities(defined('txt_menu_home') ? txt_menu_home : ''); ?>">
            <?php echo defined('txt_menu_home') ? txt_menu_home : '' ?>
        </a>
        <a href="<?php echo $this->url->get($lang_url.'/notfound'); ?>" target="_self" title="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>">
            <?php echo isset($menu_bread) ? $menu_bread : '' ?>
        </a>
    </div>
</div>
<?php } ?>
<div class="padding-block text-center">
    <div class="container">
        <img src="<?php echo $this->url->getStatic('frontend/'); ?>images/error-404.svg" alt="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>" title="<?php echo isset($menu_bread) ? strip_tags($menu_bread) : '' ?>">
        <?php echo defined('txt_notfound_description') ? str_replace('|||LANG|||',$lang_url_slashed,txt_notfound_description) : ''; ?>
    </div>
</div>