<script>
    $( document ).ready(function() {
        $('form[name=page-form]').submit(function(event) {
            var valid = true;
            if($('input[name=txtKeyword]').val() == '') {
                $('.msg-keyword').text('Keyword field is required.');
                $('#txtKeyword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-keyword').text('');
                $('#txtKeyword').removeClass("border-red");
            }
            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=sbmPage]').prop('disabled', true);
            }
        });
    });
</script>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Page</h3>
    </div>
</div>
<?php if(!empty($messages['message']))
{
    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage']?>">
        <?php echo $messages['message']; ?>
    </p>
<?php }	?>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Edit
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form name="page-form" id="page-form" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <input type="hidden" name="save" id="save" value="<?php echo \Bincg\Models\BinLanguage::GENERAL ;?>" />
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Keyword <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["page_keyword"]) ? $formData["page_keyword"] : "" ?>" id="txtKeyword" name="txtKeyword" class="form-control col-md-7 col-xs-12 <?php echo isset($messages["keyword"]) ? $messages["status"] : ""; ?>" type="text">
                            <span class="text-danger msg-keyword"><?php echo isset($messages["keyword"]) ? $messages["keyword"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtStyle">Style  </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea  class="form-control" id="txtStyle" name ="txtStyle" style="width: 750px;height: 212px;"><?php echo isset($formData["page_style"]) ? $formData["page_style"] : ""; ?></textarea>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmPage" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="<?php echo $this->url->get("/dashboard/list-page"); ?>">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <ul class="nav nav-pills" role="tablist">
                <?php
                foreach ( $formData['arr_language'] as $code => $lang ){
                    $active = $formData['lang_current']== $code?"active":"";
                    ?>
                    <li role="presentation" class="<?php echo $active; ?>"><a href="#<?php echo $code ?>translate" aria-controls="<?php echo $code ?>translate" role="tab" data-toggle="tab"><?php echo $lang; ?></a></li>
                <?php } ?>
            </ul>
            <div class="tab-content">
                <?php foreach ($formData['arr_language'] as $code => $lang ) {
                    $active = $formData['lang_current']== $code?"active":"";
                    ?>
                    <div role="tabpanel" class="tab-pane <?php echo $active; ?>" id="<?php echo $code; ?>translate">
                        <br>
                        <form name="page-form<?php echo $code; ?>" id="page-form<?php echo $code; ?>" action="" data-parsley-validate class="form-horizontal form-label-left" method="post">
                            <input type="hidden" name="save" id="save" value="<?php echo $code; ?>" />
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Name <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["page_name"]) ? $formData['arr_translate'][$code]["page_name"] : "" ?>" type="text" id="txtName<?php echo $code; ?>" name="txtName"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages[$code]["name"])) ? $messages["status"] : ""; ?>">
                                    <span class="text-danger msg-name-<?php echo $code; ?>"><?php echo isset($messages[$code]["name"]) ? $messages[$code]["name"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Title <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["page_title"]) ? $formData['arr_translate'][$code]["page_title"] : "" ?>" type="text" id="txtTitle<?php echo $code; ?>" name="txtTitle"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages[$code]["title"])  ) ? $messages["status"] : ""; ?>">
                                    <span class="text-danger msg-title-<?php echo $code; ?>"><?php echo isset($messages[$code]["title"]) ? $messages[$code]["title"] : "";?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta keyword <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea style="height: 100px;" id="txtMetaKey<?php echo $code; ?>" class="form-control <?php echo (isset($messages[$code]["meta_keyword"])) ? $messages["status"] : ""; ?>" name ="txtMetaKey"  ><?php echo isset($formData['arr_translate'][$code]["page_meta_keyword"]) ? $formData['arr_translate'][$code]["page_meta_keyword"] : "" ?></textarea>
                                    <span class="text-danger msg-metakeyword-<?php echo $code; ?>"><?php echo isset($messages[$code]["meta_keyword"]) ? $messages[$code]["meta_keyword"] : "";?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta description <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea style="height: 100px;" id="txtMetaDesc<?php echo $code; ?>" class="form-control <?php echo (isset($messages[$code]["meta_description"])) ? $messages["status"] : ""; ?>" name ="txtMetaDesc"  ><?php echo isset($formData['arr_translate'][$code]["page_meta_description"]) ? $formData['arr_translate'][$code]["page_meta_description"] : "" ?></textarea>
                                    <span class="text-danger msg-metadescription-<?php echo $code; ?>"><?php echo isset($messages[$code]["meta_description"]) ? $messages[$code]["meta_description"] : "";?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta Image</label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input placeholder="1920 x 960"
                                           maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["page_meta_image"]) ? $formData['arr_translate'][$code]["page_meta_image"] : "" ?>"
                                           id="txtMetaImage<?php echo $code; ?>"
                                           name="txtMetaImage"
                                           class="form-control col-md-7 col-xs-12" type="text" >
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Content
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea  id="txtContent<?php echo $code; ?>" class="form-control" name ="txtContent"  ><?php echo isset($formData['arr_translate'][$code]["page_content"]) ? $formData['arr_translate'][$code]["page_content"] : "" ?></textarea>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button name="sbmPage<?php echo $code; ?>" type="submit" class="btn btn-success">Save change</button>
                                </div>
                            </div>
                            <script>
                                $( document ).ready(function() {
                                    $('#txtName<?php echo $code; ?>').on('input', function() {
                                        var id = <?php echo isset($formData['arr_translate'][$code]["page_id"]) ? $formData['arr_translate'][$code]["page_id"] : -1;?>;
                                        if(id < 0) {
                                            var str = $(this).val();
                                            $('#txtTitle<?php echo $code; ?>').val(str);
                                            $('#txtMetaKey<?php echo $code; ?>').val(str);
                                            $('#txtMetaDesc<?php echo $code; ?>').val(str);
                                        }
                                    });
                                    var oFCKeditor2 = new FCKeditor('txtContent<?php echo $code; ?>') ;
                                    oFCKeditor2.Height = '400';
                                    oFCKeditor2.Width = '700';
                                    oFCKeditor2.ToolbarSet = "Default" ;
                                    oFCKeditor2.Basepath = '../backend/fckeditor/';
                                    oFCKeditor2.ReplaceTextarea() ;
                                    $('form[name=page-form<?php echo $code; ?>]').submit(function (event) {
                                        valid = true;
                                        if($('#txtName<?php echo $code; ?>').val() == '') {
                                            valid = false;
                                            $('.msg-name-<?php echo $code;?>').text("Name field is required.");
                                            $('#txtName<?php echo $code; ?>').addClass("border-red");
                                        } else {
                                            $('.msg-name-<?php echo $code;?>').text('');
                                            $('#txtName<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if($('#txtTitle<?php echo $code; ?>').val() == '') {
                                            $('.msg-title-<?php echo $code; ?>').text('Title field is required.');
                                            $('#txtTitle<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-title-<?php echo $code; ?>').text('');
                                            $('#txtTitle<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if($('#txtMetaKey<?php echo $code; ?>').val() == '') {
                                            $('.msg-metakeyword-<?php echo $code; ?>').text('Meta keyword field is required.');
                                            $('#txtMetaKey<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-metakeyword-<?php echo $code; ?>').text('');
                                            $('#txtMetaKey<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if($('#txtMetaDesc<?php echo $code; ?>').val() == '') {
                                            $('.msg-metadescription-<?php echo $code; ?>').text('Meta description field is required.');
                                            $('#txtMetaDesc<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-metadescription-<?php echo $code; ?>').text('');
                                            $('#txtMetaDesc<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if( ! valid ) event.preventDefault();
                                        if( valid ) {
                                            $('#sbmPage<?php echo $code; ?>').prop('disabled', true);
                                        }
                                    });
                                });
                            </script>
                        </form>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>