<script>
    $(document).ready(function () {

        var id = <?php echo $oldinput["id"]; ?>;
        $('#txtName').on('input', function () {
            var str = $(this).val();
            if (id == -1) {
                var str_slug = slugify(str);
                $('#txtKeyword').val(str_slug);
            }
        });
        $('form[name=type-form]').submit(function (event) {
            var valid = true;
            if ($('input[name=txtName]').val() == '') {
                $('.msg-name').text('Name field is required.');
                $('#txtName').addClass("border-red");
                valid = false;
            } else {
                $('.msg-name').text('');
                $('#txtName').removeClass("border-red");
            }
            if ($('input[name=txtInsertTime]').val() == '') {
                $('.msg-time').text('Insert Time field is required.');
                $('#txtInsertTime').addClass("border-red");
                valid = false;
            } else {
                $('.msg-time').text('');
                $('#txtInsertTime').removeClass("border-red");
            }
            if ($('textarea[name=txtDesc]').val() == '') {
                $('.msg-description').text('Description field is required.');
                $('#txtDesc').addClass("border-red");
                valid = false;
            } else {
                $('.msg-description').text('');
                $('#txtDes').removeClass("border-red");
            }
            if ($('input[name=txtKeyword]').val() == '') {
                $('.msg-keyword').text('Keyword field is required.');
                $('#txtKeyword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-keyword').text('');
                $('#txtKeyword').removeClass("border-red");
            }
            if (!valid) event.preventDefault();
            if (valid) {
                $('button[name=sbmType]').prop('disabled', true);
            }
        });
    });

</script>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Album</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Create
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br/>
                <form name="type-form" id="type-form" data-parsley-validate class="form-horizontal form-label-left"
                      method="post">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtName">Name <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($oldinput["name"]) ? $oldinput["name"] : "" ?>" type="text"
                                   id="txtName" name="txtName"
                                   class="form-control col-md-7 col-xs-12 <?php echo isset($messages["name"]) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-name"><?php echo isset($messages["name"]) ? $messages["name"] : "" ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Keyword <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255"
                                   value="<?php echo isset($oldinput["keyword"]) ? $oldinput["keyword"] : "" ?>"
                                   id="txtKeyword" name="txtKeyword"
                                   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["keyword"]) || isset($messages["exist"])) ? $messages["status"] : ""; ?>"
                                   type="text">
                            <span class="text-danger msg-keyword"><?php echo isset($messages["keyword"]) ? $messages["keyword"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Description <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtDesc" name="txtDesc"
                                      style="height: 212px;"><?php echo isset($oldinput["description"]) ? $oldinput["description"] : ""; ?></textarea>
                            <span class="text-danger msg-description"><?php echo isset($messages["description"]) ? $messages["description"] : "" ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Insert Time <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input value="<?php echo isset($oldinput["insert_time"]) ? $oldinput["insert_time"] : "" ?>"
                                   type="text" id="txtInsertTime" name="txtInsertTime"
                                   class="form-control col-md-7 col-xs-12 <?php echo isset($messages["insert_time"]) ? $messages["status"] : ""; ?>">MM/DD/YYYY
                            H:M:S<br>
                            <span class="text-danger msg-time"><?php echo isset($messages["insert_time"]) ? $messages["insert_time"] : "" ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Is Home </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radIsHomeActive"
                                                                  value="Y" <?php echo (isset($oldinput["is_home"]) && $oldinput["is_home"] == "Y") ? "checked" : ''; ?>>Yes<span
                                        class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radIsHomeActive"
                                                                  value="N" <?php echo (isset($oldinput["is_home"]) && $oldinput["is_home"] == "N") ? "checked" : ''; ?>>No<span
                                        class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Active </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive"
                                                                  value="Y" <?php echo (isset($oldinput["active"]) && $oldinput["active"] == "Y") ? "checked" : ''; ?>>Yes<span
                                        class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive"
                                                                  value="N" <?php echo (isset($oldinput["active"]) && $oldinput["active"] == "N") ? "checked" : ''; ?>>No<span
                                        class="checkmark"></span></label>
                        </div>
                    </div>

                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmType" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="<?php echo $this->url->get("/dashboard/list-album"); ?>">Cancel</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
